### ISSUE TITLE
Why having a custom jdbc mixing and not using something like sequel?

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-input-jdbc#1]
I wonder why do we need something like the custom jdbc mixing if we could be using a library like https://github.com/jeremyevans/sequel that has actually adapters for

```
 ADO, Amalgalite, CUBRID, DataObjects, DB2, DBI, Firebird, FoundationDB SQL Layer, IBM_DB, Informix, JDBC, MySQL, Mysql2, ODBC, OpenBase, Oracle, PostgreSQL, SQLAnywhere, SQLite3, Swift, and TinyTDS.
```

out of the box.

is there any design reason that makes us avoid using Sequel?

**Comment by talevy** [comment]
We do use Sequel :)
