### ISSUE TITLE
Logstash jdbc plugin - filter issue

### ISSUE THREAD

**Issue by srinvas** [logstash-plugins/logstash-input-jdbc#102]
I am using below filter to copy content in COLUMN1 into COLUMN2.
`filter {        
mutate {
add_field => {
  "COLUMN2" => "%{COLUMN1 }"   
}
}
}
`
But if any value in COLUMN1  is null then its copying the value as  %{COLUMN1 } into COLUMN2
How to avoid it printing %{COLUMN1 } and print null

**Comment by wiibaa** [comment]
Such question are better to be asked on https://discuss.elastic.co/c/logstash
But as your are already here for this one, you should be able to wrap your filter with a condition
````
filter {
  if [COLUMN1] {
    mutate { add_field => { "COLUMN2" => "%{COLUMN1 }" }
  }
}
