### ISSUE TITLE
 @sql_last_start = Time.now.utc maybe is later

### ISSUE THREAD

**Issue by whybangbang** [logstash-plugins/logstash-input-jdbc#104]
we use jdbc plugin in our' system,and some update don't be updated to es ,so we review this plugin'code,we guess  '@sql_last_start = Time.now.utc' maybe later,if user commit between sql run time,these commit won't be synchronize.

thank you for your reply,thank you !

**Comment by untergeek** [comment]
Can you give some more context here, please?  It would be easier to try to reproduce this if you provided some examples and/or samples.

**Comment by suyograo** [comment]
Closing because of no updates
