### ISSUE TITLE
Cannot install the plugin on windows

### ISSUE THREAD

**Issue by ReddySk** [logstash-plugins/logstash-input-jdbc#105]
Hello, 

I am new with elastic search and trying to install this plugin on Win 7 Professional.

Using the standard way it doesn't work. 
```
E:\Utility\elasticsearch-2.1.0\bin>plugin install logstash-input-jdbc
-> Installing logstash-input-jdbc...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/logstash-input-jdbc/2.1.0/logstash-input-jdbc-2.1.0.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
```

when try to test the URL in browser then getting error:
```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>elasticsearch/release/org/elasticsearch/plugin/logstash-input-jdbc/2.1.0/logstash-input-jdbc-2.1.0.zip</Key>
  <RequestId>22A4FCB79790F13F</RequestId>
  <HostId>n9kTIJA4rQ4ql787asQCnZL9waAMYMfZO1A46d9ZisBVIDf17yu+Uqom2cGJKQ+rQ/oxpmX4LWY=</HostId>
</Error>
```
Can you please advise how to install it? 

Thanks in advance
Regards
Reddy

**Comment by gusega** [comment]
I'm having the same problem windows7

**Comment by suyograo** [comment]
This is a Logstash plugin, not Elasticsearch. You are trying to install this plugin on Elasticsearch.

**Comment by jitendrasoni** [comment]
Replying too late - I had faced the same problem but here this is plugin for the Logstash not for the ElasticSearch - that's correct.

I am using Window 10 but not getting these plugin withing Lagstash - when I ran this through window command, it was showing not a recognized internal or external commands.
