### ISSUE TITLE
"sql_last_start" updated after every query or on logstash stopped?

### ISSUE THREAD

**Issue by vikram-gupta** [logstash-plugins/logstash-input-jdbc#106]
Our requirement is to index multiple tables from a jdbc source into Elastic Search and thus we have written multiple "jdbc input" tags in the configuration file. Our tables have a "updated_at" field which we use to compare with "sql_last_start" to get only the updated rows for indexing.

Doubt is - When would "sql_last_start" get updated? 

After every query or After the logstash process executes all our queries?

We would ideally like the second option to happen so that all tables are queried with same "sql_last_start".

**Comment by suyograo** [comment]
Hey, today `sql_last_start` gets written when LS is shutting down. We are changing this to happen after queries get executed.

https://github.com/logstash-plugins/logstash-input-jdbc/pull/94
