### ISSUE TITLE
can't connect to postgres

### ISSUE THREAD

**Issue by jney** [logstash-plugins/logstash-input-jdbc#107]
i'm trying to run  logstash on docker with this [tutorial](https://www.elastic.co/blog/logstash-jdbc-input-plugin)

```
$ logstash --version
logstash 2.1.1
$ java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
```

having this conf :

```
input {
    jdbc {
        jdbc_connection_string => "jdbc:postgresql://postgres@db:5432/base"
        jdbc_user => "postgres"
        jdbc_driver_library => "/var/app/postgresql-9.4.1207.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        statement => "SELECT * from posts"
    }
}
```

i've got the following error : 

```
The error reported is:
  Java::OrgPostgresqlUtil::PSQLException: FATAL: role "root" does not exist
```

i must specify `jdbc_connection_string` as `"jdbc:postgresql://postgres@db:5432/base"` (note i forced the user)

anyway, i've got the following error; althrough i can connect with the same connection string using `psql` client.
 
```
The error reported is:
  Java::OrgPostgresqlUtil::PSQLException: The connection attempt failed.
```

**Comment by wiibaa** [comment]
Having a quick look around the internet, the correct syntax for the jdbc connection string for postgres seems to be **jdbc:postgresql://host:port/database?user=username**, did you already try this one. Please have in mind that JDBC and psql client are two totally different clients.

**Comment by jney** [comment]
my bad about the jdbc syntax. indeed it works.
what's the point  of `jdbc_user` ? if it is declared, `user=username` shouldn't be necessary, no ?

**Comment by willpriceb** [comment]
I've experienced exactly the same issue, surely `jdbc_user` should be integrated into the connection string? This seems like a bug in implementation or documentation.

**Comment by dvcrn** [comment]
Please add this to the documentation. I wasted hours debugging this problem. I had 
```
        jdbc_user => "myuser"
```

in my configuration but kept getting a generic `Sequel::DatabaseConnectionError` error. Adding `?user=myuser` to the connection string suddenly fixed everything.

**Comment by vkjangra1209** [comment]
This helped me a lot..Please update the docs..

**Comment by jkrempl** [comment]
> Please add this to the documentation. I wasted hours debugging this problem. I had
> 
> ```
>         jdbc_user => "myuser"
> ```
> 
> in my configuration but kept getting a generic `Sequel::DatabaseConnectionError` error. Adding `?user=myuser` to the connection string suddenly fixed everything.

This
