### ISSUE TITLE
mysql mariadb connector error.

### ISSUE THREAD

**Issue by MdSarfarazKhan** [logstash-plugins/logstash-input-jdbc#110]
I'm using jdbc input plugin for reading some data from mysql. I'm using mariadb mysql connector and getting the below error.
`{:timestamp=>"2016-01-15T15:12:55.910000+0530", :message=>"Unable to connect to database", :error_message=>"com.mysql.jdbc.Driver not loaded, try installing jdbc-mysql gem", :level=>:error}
{:timestamp=>"2016-01-15T15:12:55.916000+0530", :message=>"The error reported is: \n  com.mysql.jdbc.Driver not loaded, try installing jdbc-mysql gem"}`

I have the below configuration.
`input {
   jdbc {
     jdbc_driver_library => "/path/mariadb-java-client-1.1.8.jar"
     jdbc_driver_class => "org.mariadb.jdbc.Driver"
     jdbc_connection_string => "jdbc:mysql://localhost:3306/test"
     jdbc_user => "test"
     jdbc_password => "test"
     record_last_run => "true"
     schedule => "* * * * *"
     statement => "SELECT * from xyz where last_modified > :sql_last_start"
   }
}`

The same runs with mysql connector driver.

**Comment by allanmc** [comment]
Your JDBC connection string says `jdbc:mysql` - it should say `jdbc:mariadb` when using MariaDB Connector/J.

Try with:
`
jdbc_connection_string=>"jdbc:mariadb://localhost:3306/test"
`

**Comment by suyograo** [comment]
Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
