### ISSUE TITLE
Logstash 2.x last_run_metadata_path not working (MySQL)

### ISSUE THREAD

**Issue by marcinkubica** [logstash-plugins/logstash-input-jdbc#111]
Hi

Tried all versions of Logstash 2 and last_run_metadata_path is not saving.

Will be grateful if someone can also try and tell if they observe this.

Tried without path for last_run_metadata_path and it's not saving to $HOME either also tried enforcing  values and no joy.

Also if I set path for metadata to a non existent folder it's not complaining. (usually logstash is complaining about bad config, right?)

Java version ```1.8.0_66-b17 64bit```
MySQL driver ```mysql-connector-java-5.1.37-bin.jar and .38``

Ta
Marcin

**Comment by leifurhauks** [comment]
I believe I'm experiencing the same problem, I have explicitly set `record_last_run => true` and I've set `last_run_metadata_path` to an absolute path.

**Comment by leifurhauks** [comment]
Update: when I run with a schedule ( `schedule => "* * * * *"` ) instead of running it one-off, the last run metadata is recorded *after I stop logstash*. Until then, it is not recorded and `:sql_last_run` is set to the unix epoch every time.

**Comment by marcinkubica** [comment]
@leifurhauks many thanks for your findings!

**Comment by leifurhauks** [comment]
After updating to version 3.0.0 of the plugin (via `bin/plugin update logstash-input-jdbc`) it seems to be working correctly (but `:sql_last_start` has to be changed to `:sql_last_value`)

**Comment by marcinkubica** [comment]
@leifurhauks Many thanks mate. Any chance to list parameter names? Seems docs are out of date on elastic website. Many thanks!

**Comment by leifurhauks** [comment]
The `master` branch docs are more up to date: https://www.elastic.co/guide/en/logstash/master/plugins-inputs-jdbc.html

**Comment by marcinkubica** [comment]
@leifurhauks cheers!

It's a bit unfortunate this parameter when used in SQL statement file doesn't store date last seen from SQL statement. 

Is there any way to do that?

**Comment by leifurhauks** [comment]
Suppose you want it to store the value in a column 'created', you would set
use_column_value to true and set tracking_column to "created". Note that it
will store the value of that column in the last row of your query result,
so you probably will want to order by that column.

Otherwise if use_column_value is false, it will use the local system time
of the last run.

**Comment by leifurhauks** [comment]
Ah, I only saw the first half of your post. I don't know why it's not
working :-/
Le 2016-01-28 09:22, "Leif Halldór Ásgeirsson" <leifurhauks@gmail.com> a
écrit :

> Suppose you want it to store the value in a column 'created', you would
> set use_column_value to true and set tracking_column to "created". Note
> that it will store the value of that column in the last row of your query
> result, so you probably will want to order by that column.
>
> Otherwise if use_column_value is false, it will use the local system time
> of the last run.

**Comment by leifurhauks** [comment]
Did you set `use_column_value => true`?

**Comment by marcinkubica** [comment]
@leifurhauks I didn't use use_column_value 
i'll be checking this back in few days. Many thanks for your help so far!

**Comment by marcinkubica** [comment]
Cool works m8 :D

![image](https://cloud.githubusercontent.com/assets/1593987/12747976/2dfd021e-c99f-11e5-8e28-88c134d963d6.png)
