### ISSUE TITLE
Default value for last_run_metadata_path config option is specific to OS X

### ISSUE THREAD

**Issue by leifurhauks** [logstash-plugins/logstash-input-jdbc#113]
The default value for the last_run_metadata_path config option appears to be specific to OS X:

`"/Users/suyog/.logstash_jdbc_last_run"`

**Comment by untergeek** [comment]
That's very unusual.  [This is the code that generates the default](https://github.com/logstash-plugins/logstash-input-jdbc/blob/master/lib/logstash/inputs/jdbc.rb#L133):

```ruby
  # Path to file with last run time
  config :last_run_metadata_path, :validate => :string, :default => "#{ENV['HOME']}/.logstash_jdbc_last_run"
```

What operating system are you using?  Which version of Logstash?  Is it a packaged version?

**Comment by leifurhauks** [comment]
Ah, I was referring to the documentation, which perhaps was built on OS X.

**Comment by untergeek** [comment]
Can you send a link where you found this?  It's not embedded in the code as a hard link, nor is it in the [plugin documentation](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html) where I can see.

**Comment by leifurhauks** [comment]
Already the docs [seem to have been revised to fix this](https://www.elastic.co/guide/en/logstash/master/plugins-inputs-jdbc.html#plugins-inputs-jdbc-last_run_metadata_path):

>Default value is $USER_HOME/.logstash_jdbc_last_run

**Comment by leifurhauks** [comment]
Although the last revision was a while ago, so I have no idea how that happened? I know I had copy/pasted that line from the docs, but they seem to be fine now.

**Comment by leifurhauks** [comment]
Just now I saw it again at https://www.elastic.co/guide/en/logstash/master/plugins-inputs-jdbc.html

![screenshot from 2016-01-25 15-05-49](https://cloud.githubusercontent.com/assets/5378335/12562843/3c612fea-c375-11e5-9dda-81497e532511.png)

Seems like something to do with the system configuration of wherever the docs are served from. Based on the fact that it doesn't show up every time, it may be happening on one node of several behind a load balancer.

**Comment by untergeek** [comment]
That's something we can look into.  Thanks for following up.

**Comment by dannygoulder** [comment]
Hi.  Just stumbled across this - it currently shows /home/ph/.logstash_jdbc_last_run for me, so looks like this still needs fixing...
