### ISSUE TITLE
PSQLException: ERROR: column "sql_last_start" does not exist

### ISSUE THREAD

**Issue by tianchao-haohan** [logstash-plugins/logstash-input-jdbc#114]
Java::OrgPostgresqlUtil::PSQLException: ERROR: syntax error at or near ":"
  Position: 56: SELECT * from si_promotion_request where request_date >:sql_last_start {:level=>:error}
Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::OrgPostgresqlUtil::PSQLException: ERROR: syntax error at or near ":"
  Position: 56>, :level=>:warn}

Here is the configuration file:

input {
    jdbc {
        jdbc_connection_string => "jdbc:postgresql://mydbhost:5432/sidtestDB"
        jdbc_user => "user"
        jdbc_password => "password"
        jdbc_driver_library => "postgresql-9.4-1200-jdbc41.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        schedule => "* * * * *"
        statement => "SELECT * from si_promotion_request where request_date >:sql_last_start"
    } 
}
output {
  elasticsearch { hosts => localhost }
  stdout { codec => json_lines }
}

**Comment by untergeek** [comment]
Have you recently updated the JDBC input plugin?  If you are using plugin v3.0.0, then `:sql_last_start` has been replaced by `:sql_last_value`.  See #57 and #108.  And for a bit of documentation, see [this comment](https://github.com/logstash-plugins/logstash-input-jdbc/issues/57#issuecomment-169436652).

**Comment by tianchao-haohan** [comment]
It works now with sql_last_value.
Would you please update the guide in elk page, where the sql_last_start was still used: 
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-record_last_run

**Comment by suyograo** [comment]
@untergeek can you add the example in https://github.com/logstash-plugins/logstash-input-jdbc/issues/57#issuecomment-169436652 to the docs? It'll be really helpful for new users

**Comment by untergeek** [comment]
@suyograo roger that.

**Comment by untergeek** [comment]
Closed by #115
