### ISSUE TITLE
It takes me a lot of time to install the plugin successfully.

### ISSUE THREAD

**Issue by tianchao-haohan** [logstash-plugins/logstash-input-jdbc#116]
\curl -sSL https://get.rvm.io | bash
sudo rvm install jruby
source $HOME/.rvm/scripts/rvm 
gem install bundle

git clone https://github.com/logstash-plugins/logstash-input-jdbc.git
cd logstash-input-jdbc
bundle install
bundle exec rspec
gem build logstash-input-jdbc.gemspec
/your/local/logstash/bin/plugin install /your/local/plugin/logstash-input-jdbc.gem

It maybe useful to new users. It will be quite helpful if you can package the plugin together with logstash and jruby with the one-click install.

**Comment by untergeek** [comment]
@tianchao-haohan, both JRuby and the plugin _are_ included in the base install of Logstash.  I'm not sure what you're running into.  How have you installed Logstash?  From git?  We have [package repositories](https://www.elastic.co/guide/en/logstash/current/package-repositories.html) and [two flavors](https://www.elastic.co/downloads/logstash) of the compressed archive available to download: Standard and "All plugins."

**Comment by suyograo** [comment]
@tianchao-haohan LS 2.1 and above have JDBC input packaged by default
