### ISSUE TITLE
Is there a way to remove nil fields?

### ISSUE THREAD

**Issue by casimirextreme** [logstash-plugins/logstash-input-jdbc#117]
Hi,

Is there a way to remove nil fields?

I've tried with a ruby code:
 ruby {
    code => "event.to_hash.delete_if {|field, value| value == '' }"
 }

But it has no effect.

Any idea?

**Comment by casimirextreme** [comment]
That might help others, this is working:

  ruby {
     code => "event.to_hash.delete_if {|field, value| value == nil }"
  }

**Comment by Simakink** [comment]
not work with logstash 5.5
