### ISSUE TITLE
Make jdbc_user config optional

### ISSUE THREAD

**Issue by mircopolo** [logstash-plugins/logstash-input-jdbc#118]
Would it be possible to make the jdbc_user config parameter optional, although it is only possible on the sql server jdbc driver, I do have a use case where I need to use integrated security with the MS Sql server jdbc driver and this is currently not possible without altering the plugin myself.

**Comment by Tollefsen** [comment]
+1

**Comment by Tollefsen** [comment]
Trouble with this after altering the plugin. I removed the "required" tag on jdbc_user and altered the opts to send user as nil if no user is defined.

For some reason I can not get the integrated security to work after the alter.
My thought were that if I run logstash as the user with access to my MS SQL server, the server would recognize the owner of the process and accept the connection. Everything is on a local server.
(Big possibility that I have misunderstood how Integrated Security works, first day trying it out.)

The error I get after running logstash is a normal "Login failed for user ..." which I think means that the plugin works as intended, but the login credentials are not working. Is there a possibility that when jdbc uses Sequel a new process starts with new/other owner? Have only tried a few hours. Hopefully someone have some more insight and can enlighten me.

**Comment by mircopolo** [comment]
Sounds like you have everything covered on the logstash end, it seems more like the windows principal may not have correct permission set on the specific database, there are a few steps after creating  a sql server  login mapping roles for databases  etc that it is worth double checking.

https://msdn.microsoft.com/en-us/library/aa337562.aspx

**Comment by Tollefsen** [comment]
I'm confident that my windows credentials have the permissions and security configurations correct. I have access when using the same credentials on other programs, like Microsoft SQL Server Management Studio og Visual Studio server explorer.

I'm also using logstash configuration that I have tried and confirmed working using SQL authentication. That way I know the driver and statement and such are working configurations.

That's the reason why I believe the credentials used by logstash is altered in some way, like starting a process with another user attached to it. It might even be the driver, I have little experience with such.

**Comment by mircopolo** [comment]
Not sure if is subsequent changes in the to newer versions of the plugin or MS JDBC driver, but the following configuration  now works for me for integrated windows security,  So I am closing this ticket as  I believe it is no longer required.

Tested with logstash-input-jdbc 4.1.3. and MS JDBC driver v6.0 on WIN 7 x64

Steps 
1) Input config similar to below

jdbc {
....
      jdbc_driver_library => "C:/sqljdbc_6.0/enu/jre8/sqljdbc42.jar"
      jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      jdbc_connection_string => "jdbc:sqlserver://XXX;databaseName=XXX;integratedsecurity=true"
      jdbc_user => nil
...
}

2) Add sql_auth.dll to java.library.path ( such as in logstash\bin\setup.bat) 
set JAVA_OPTS=%JAVA_OPTS% -Djava.library.path=C:\sqljdbc_6\enu\auth\x64
