### ISSUE TITLE
@sql_last_value not working with tracking column

### ISSUE THREAD

**Issue by pankajmalhotra** [logstash-plugins/logstash-input-jdbc#119]
I am trying to use following value in jdbc plugin but its not accepting "id" column.
use_column_value => true
tracking_column => "id"

statement => "SELECT id ,AccountId FROM summary where id > :sql_last_value"
But sql_last_value keeps on taking timestamp instead of id from summary table.

Please suggest

Logstash: 2.2.1
logstash-input-jdbc : 3.0.0
java version "1.8.0_66

**Comment by untergeek** [comment]
@pankajmalhotra have you tried deleting `ENV['HOME']/.logstash_jdbc_last_run`, or whatever you've set `last_run_metadata_path` to?  If you ran it even once before changing to use a tracking column, then it will have a timestamp in the aforementioned file.  This will be corrected after deleting this file.

**Comment by untergeek** [comment]
I'm closing this ticket due to non-response.  Feel free to reopen it if you are still experiencing this problem.
