### ISSUE TITLE
Logstash jdbc input : Read password from external file

### ISSUE THREAD

**Issue by biswajit86** [logstash-plugins/logstash-input-jdbc#120]
Hi, We started using logstash jdbc input in a few of our configs and so far it has been working really great. We do have some problems with the way the connection credentials are passed in

 We do not store password for any of our apps in our config files.
* First of all, it violates our security guidelines
* Second, whenever we change a password , we do not want to change the configs for every since service that we have.

Therefore, we store our password in files on unix host and apply permissions using chmod to restrict access to the relevant applications.

However, logstash currently does not offer any other mechanism to read password files. Could you please add a config in jdbc-input plugin to read password from an external file instead of passing in a naked password.

**Comment by bwgriffith** [comment]
We are facing the same issue, and would be very interested in a solution for this as well.

**Comment by dariko** [comment]
I created a pull request (#128) implementing this as `jdbc_password_filepath` parameter

**Comment by suyograo** [comment]
Fixed in #128
