### ISSUE TITLE
JDBC sql_last_value, tracking_column option is not working properly used

### ISSUE THREAD

**Issue by ShowmethemoneyGitHub** [logstash-plugins/logstash-input-jdbc#122]
I'm sorry I did not get a good English
Use the current sql server 2008. and My OS is Windows 7
My setting ↓↓↓↓↓

input {
  jdbc {
    jdbc_driver_library => "C:\Program Files\Java\jre1.8.0_73\lib\ext\sqljdbc42.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    jdbc_connection_string => "jdbc:sqlserver://localhost:1433;database=MyDB"
    jdbc_user => "xxx"
    jdbc_password => "xxx"
    statement => "SELECT *  FROM TABLE_NAME WHERE My_Column > :sql_last_value"
    use_column_value => "true"
    tracking_column => "My_Column "
    last_run_metadata_path => "C:\\.logstash_jdbc_last_run"
    record_last_run => "true"
    schedule => "* * * * *" 
  }
}

When you run 
"**← [33m tracking_column not found in dataset. {: Tracking column =>" By Column ",: level =>: warn} ← [0m**" 
comes out of the error

logstash version : 2.2.0
jdbc-input : 3.0

please Help me...

**Comment by untergeek** [comment]
@ShowmethemoneyGitHub please raise usage questions at https://discuss.elastic.co/c/logstash

Github issues are for bug reports and code improvement submissions

**Comment by ShowmethemoneyGitHub** [comment]
Thank you for your answers

The problem was well resolved!
