### ISSUE TITLE
Logstash JDBC Input plugin : Migrate data from mysql in batch count

### ISSUE THREAD

**Issue by chitrapillai** [logstash-plugins/logstash-input-jdbc#129]
I have a table of 20GB data having 50 million rows. Need to migrate to ElasticSearch using logstash jdbc input plugin. I have tried all basic implementation but need help in migrating data in batch i.e only 10,000 rows at a time. I am not sure how and where to specify this count and how to update it the next time i run logstash. Please help me solve this issue

**Comment by untergeek** [comment]
Logstash presently does not allow for batched ingest in any plugin.  If you truly are compelled to ingest in batches, you would have to write your own ingest tool (even if it forwards to Logstash).

The JDBC input does allow for using an incrementing column value (either numeric or timestamp) so it will only query rows not previously queried.  This is the `sql_last_value` configuration option.

For future reference, GitHub issues are for bug reports and feature requests.  Usage questions should be directed to our discussion forums at https://discuss.elastic.co/c/logstash
