### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by MaherBTA** [logstash-plugins/logstash-input-jdbc#130]
Hi,

From what i know, logstash uses sql_last_value to save the last successful statment execution.
So to read new line you can compare the sql_last_value with the modification time the column.

But isn't that too heavy, to check all the database for new data?
isn't it better to use a trigger on the database and send the new data to logstash manually?

Thank you!

**Comment by untergeek** [comment]
Ideally, when using `sql_last_value` you're not doing time-based, but an incrementing column value.  But in either case, it's not that hard for a database to return values greater than a timestamp or with values higher than an incremented column.

If you were to write your own trigger on a database to send changes, I don't believe it will be a lot faster or less taxing than running queries that poll for higher values.
