### ISSUE TITLE
SQL parse error with \"

### ISSUE THREAD

**Issue by lgmarmolejo** [logstash-plugins/logstash-input-jdbc#138]
Hi -
I am experiencing syntax problem with they query generated by the plugin.
I have configured the query  =  MY-QUERY
plugin generates:    SELECT count(*) AS \"COUNT\" FROM ( MY-QUERY) AS \"T1\" LIMIT 1;

The problem is reproduced when I ran the query on the command line (beeline). and the problem goes away when I remove the \" as follows:
    SELECT count(*) AS COUNT FROM ( MY-QUERY) AS T1 LIMIT 1;

Is there a way to suppress the \" from the query produced by the plugin?

thanks,

**Comment by suyograo** [comment]
What is MY-QUERY?

Hi, can you please post these kind of questions in our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!

**Comment by PhaedrusTheGreek** [comment]
I'm also hitting this - it seems that Logstash or the JDBC library is executing this query:  `SELECT count(*) AS "COUNT" FROM ( MY-QUERY ) AS "T1" LIMIT 1;` where `MY-QUERY` is whatever we pass to `statement =>`
