### ISSUE TITLE
Handling the scenario when there is an error in SQL statement

### ISSUE THREAD

**Issue by vanga** [logstash-plugins/logstash-input-jdbc#164]
https://github.com/logstash-plugins/logstash-input-jdbc/blob/13879a3deada275edf329e36f5c712518b213989/lib/logstash/plugin_mixins/jdbc.rb#L208

If there is an error in main query, its being shadowed by this error 

```
 cannot recognize input near 'AS' '"COUNT"' 'FROM' in selection target: SELECT count(*) AS "COUNT" FROM (SELECT * FROM employee) AS "T1" LIMIT 1
```

Also this additional count query doesn't work out well with Hive SQL even when there is no error in main SQL query.
May be we should remove this logging statement?

**Comment by shubh1m** [comment]
This plugin internally uses [Sequel](https://github.com/jeremyevans/sequel) gem in the code which currently does not has a adapter for Hive. So, it is unable to build queries which Hive supports.    

HiveQL has a different query syntax than normal SQL syntax. In this case, it should be  
 `SELECT count(*) AS COUNT FROM (SELECT * FROM employee) AS T1 LIMIT 1`
