### ISSUE TITLE
Not optimal sql query when using jdbc_page_size

### ISSUE THREAD

**Issue by pdorofiejczyk** [logstash-plugins/logstash-input-jdbc#166]
I have prepared following logstash config

```
input {
 jdbc {
   jdbc_driver_library => "mysql-connector-java-5.1.39-bin.jar"
   jdbc_driver_class => "com.mysql.jdbc.Driver"
   jdbc_connection_string => "jdbc:mysql://dbhost:3306/mydb"
   jdbc_user => "user"
   jdbc_password => "password"
   statement => "SELECT * FROM test"
   jdbc_paging_enabled => "true"
   jdbc_page_size => "10000"
 }
}
output {
  stdout {  codec => json_lines  }
}
```

When I run logstash and check `SHOW PROCESSLIST;` on my db, I see following sql statements:

```
SELECT * FROM (SELECT * FROM test) as j LIMIT 10000 OFFSET 10000
```

This query reads all rows from table on each page (a few milions rows in my case) so this paging strategy is not optimal. It should do queries presented below.

```
SELECT * FROM test LIMIT 10000 OFFSET 10000
```

**Comment by axhiao** [comment]
And it is too slow! Is there a proper way to perform sql "select * from tbl" when the amount of table is large?

**Comment by catinred2** [comment]
is there any workaround for this?

**Comment by axhiao** [comment]
There is a solution for this:
jdbc_connection_string => "jdbc:mysql://localhost:3306/mydb?useCursorFetch=true"
jdbc_fetch_size => 50000

**Comment by pdorofiejczyk** [comment]
useCursorFetch will use server-side cursors, which in MySQL are implemented using temporary tables

**Comment by jbboehr** [comment]
In MySQL, a table like this:

```sql
CREATE TABLE `videos` (
  `video_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`video_id`),
  KEY `ts` (`ts`)
) ENGINE=InnoDB
```

the optimal queries should be, for count and fetch respectively:

```sql
SELECT COUNT(ts) FROM videos WHERE ts >= :sql_last_value LIMIT 1
```
```sql
SELECT * FROM videos WHERE ts >= :sql_last_value ORDER BY ts ASC LIMIT 1000
```

Is there any way to achieve this? I can add a limit to the `statement` clause, but then the count will be wrong and presumably stop import after one iteration. I'd like to avoid high offsets and large temporary tables.

**Comment by jbboehr** [comment]
After poking around the issues (#200), it appears the count query is only used for debug. In that case, the latter query of mine should partially work; it would be preferable if it continued to fetch rows until exhausting the input.

**Comment by shavo007** [comment]
@axhiao we found this issue also. Posted topic here: https://discuss.elastic.co/t/logstash-jdbc-plugin/84874

We have a large dataset. 

What you recommend to performance tune?

**Comment by izhigalko** [comment]
@jbboehr count query also used in Sequel pager

**Comment by jbboehr** [comment]
@izhigalko In MySQL at least, queries with high offsets are slow. If possible, it's better to page using a where on an indexed column.

```
mysql> select video_id from videos force index (ts) order by ts asc limit 3665722, 1;
1 row in set (1.15 sec)
```

```
mysql> explain select video_id from videos order by ts asc limit 3665722, 1;
+----+-------------+--------+-------+---------------+------+---------+------+---------+-------------+
| id | select_type | table  | type  | possible_keys | key  | key_len | ref  | rows    | Extra       |
+----+-------------+--------+-------+---------------+------+---------+------+---------+-------------+
|  1 | SIMPLE      | videos | index | NULL          | ts   | 4       | NULL | 3472469 | Using index |
+----+-------------+--------+-------+---------------+------+---------+------+---------+-------------+
```

```
mysql> select * from videos force index (ts) order by ts asc limit 3665722, 1;
1 row in set (11.72 sec)
```

```
mysql> explain select * from videos order by ts asc limit 3665722, 1;
+----+-------------+--------+------+---------------+------+---------+------+---------+----------------+
| id | select_type | table  | type | possible_keys | key  | key_len | ref  | rows    | Extra          |
+----+-------------+--------+------+---------------+------+---------+------+---------+----------------+
|  1 | SIMPLE      | videos | ALL  | NULL          | NULL | NULL    | NULL | 3472472 | Using filesort |
+----+-------------+--------+------+---------------+------+---------+------+---------+----------------+
```

```
mysql> select * from videos where ts >= '2017-05-12 17:45:20' order by ts asc limit 1;
1 row in set (0.00 sec)
```

```
mysql> explain select * from videos where ts >= '2017-05-12 17:45:20' order by ts asc limit 1;
+----+-------------+--------+-------+---------------+------+---------+------+------+-----------------------+
| id | select_type | table  | type  | possible_keys | key  | key_len | ref  | rows | Extra                 |
+----+-------------+--------+-------+---------------+------+---------+------+------+-----------------------+
|  1 | SIMPLE      | videos | range | ts            | ts   | 4       | NULL | 1127 | Using index condition |
+----+-------------+--------+-------+---------------+------+---------+------+------+-----------------------+
```

**Comment by jbboehr** [comment]
The solution I'm going with for now is to use a higher limit without paging and just wait for the scheduler.

**Comment by chaodhib** [comment]
Here is the cause of the issue:

Like explained [here](https://groups.google.com/d/msg/sequel-talk/aATR1IXa_eE/A3gr7NkAG78J), Sequel (the library used to interact with the DB) do not parse the raw SQL that is provided to it. So it cannot add a LIMIT or an OFFSET clause to the statement. The only thing it can and does do is run the statement provided by the user as a subquery.

Imo, the solution to our problem is simple but lower level: take care of the pagination ourselves (by adding manually the LIMIT and OFFSET clauses to the statement).

**Comment by jbboehr** [comment]
Disclaimer: We use MySQL, so this may only apply to that.

I'm not sure you're replying to my comment or not, but my suggestion is to have an option to not use offset for paging at all. Each subsequent page should be fetched using the previous `:sql_last_value` until their are no more records remaining.

Using an offset of 1m involves a key or table scan of 1m rows, whereas using an indexed where involves a simple btree lookup. Note that, in the former case, the last iteration will involve a full table or index scan (assuming MySQL doesn't pull of some dirty tricks, although I'm pretty sure it doesn't).

I've mostly set this up already in my own configuration, the only issue is each page has to wait for the next cron iteration. Because of this, I've set the cron to once per 15 seconds with a high limit clause, but it should be faster to import if it automatically fetches each page after the previous is done.

If the cron is set to once per second and it takes more than one second to import, does it ignore the next iteration or double up (parallel or serial)?

**Comment by chaodhib** [comment]
@jbboehr I was not replying specifically to your comment. I was explaining the root cause of the issue mentioned by OP. I also opened a [PR](https://github.com/logstash-plugins/logstash-input-jdbc/pull/232) to solve that issue.

However, I implemented what you described [here](https://github.com/chaodhib/logstash-input-jdbc/tree/pagination_second_approach). I needed to migrate several tables with millions of rows. Using this approach, I noticed a performance increase of several order of magnitude. I will try to clean up the code and make it mergeable shortly.

**Comment by jimmaay** [comment]
The second approach works wonders for importing a 1+ billion row MySQL database into elasticsearch. The bottleneck that's left is the paged MySQL query can only use 1 thread so logstash waits however long until it finishes for every paged query. On a 48 core machine this is highly inefficient and resources are barely used. Is there a way to execute multiple paged queries at a time to in essence multithread it?

**Comment by guyboertje** [comment]
@jimmaay 
We have not optimised for the paging use case with v large record sets.

We are working on a LS fleet (kind of cluster) model where one LS pipeline will prepare tasks and submit them to a Shared State endpoint and other LS instances will get tasks and execute them.
The JDBC very large dataset pagination use case is the one we use to explain how this distributed task setup should work.
We are months (if not years) away from this solution - there are many building blocks to code before we can begin coding for the JDBC paging use case specifically.

**Comment by jimmaay** [comment]
@guyboertje
The 2nd solution by @chaodhib at https://github.com/chaodhib/logstash-input-jdbc/tree/pagination_second_approach is definitely good enough for larger databases. Although it isn't as fast as it could be. For our case in order to speed things up a lot more due to mysql being single threaded for queries I just ran multiple logstash jdbc instances with a primary ID range. So 1 billion rows could be split into 10 parallel instances of 0-100 million,200-300million,300-400M, etc. Although with more than 10 instances we were running into issues with elasticsearch crashing due to instances using all the available cpu when they're not stuck on the mysql query. The only way around this is to either find a way to make mysql use multiple cores or change the plugin so it manages multiple async mysql queries and balances the CPU usage out.

**Comment by chaodhib** [comment]
I don't have enough knowledge with Ruby to implement a multi-threaded solution. However, I will try to clean up and submit a PR for the second approach. It's better than nothing. And it did the job very well for us too (a few tables to import with 10+ millions row each).

**Comment by chyt** [comment]
Sorry if I'm missing something, but can someone explain why c7c91c4 closes this issue? The docs note that paging is not enabled when using prepared statements, so I'm not sure how that helps. 

I'm currently running into a similar issue. I have a well-optimized query that becomes extremely slow (takes several minutes to execute, as opposed to a fraction of a second) when it is wrapped in the `SELECT * FROM () LIMIT X OFFSET Y` when using paging. However, I need to use paging as the dataset size causes an out of memory error in logstash when paging is off.

What is the recommended solution?

**Comment by jquery-slider7** [comment]
> [@izhigalko](https://github.com/izhigalko) In MySQL at least, queries with high offsets are slow. If possible, it's better to page using a where on an indexed column.
> 
> ```
> mysql> select video_id from videos force index (ts) order by ts asc limit 3665722, 1;
> 1 row in set (1.15 sec)
> ```
> 
> ```
> mysql> explain select video_id from videos order by ts asc limit 3665722, 1;
> +----+-------------+--------+-------+---------------+------+---------+------+---------+-------------+
> | id | select_type | table  | type  | possible_keys | key  | key_len | ref  | rows    | Extra       |
> +----+-------------+--------+-------+---------------+------+---------+------+---------+-------------+
> |  1 | SIMPLE      | videos | index | NULL          | ts   | 4       | NULL | 3472469 | Using index |
> +----+-------------+--------+-------+---------------+------+---------+------+---------+-------------+
> ```
> 
> ```
> mysql> select * from videos force index (ts) order by ts asc limit 3665722, 1;
> 1 row in set (11.72 sec)
> ```
> 
> ```
> mysql> explain select * from videos order by ts asc limit 3665722, 1;
> +----+-------------+--------+------+---------------+------+---------+------+---------+----------------+
> | id | select_type | table  | type | possible_keys | key  | key_len | ref  | rows    | Extra          |
> +----+-------------+--------+------+---------------+------+---------+------+---------+----------------+
> |  1 | SIMPLE      | videos | ALL  | NULL          | NULL | NULL    | NULL | 3472472 | Using filesort |
> +----+-------------+--------+------+---------------+------+---------+------+---------+----------------+
> ```
> 
> ```
> mysql> select * from videos where ts >= '2017-05-12 17:45:20' order by ts asc limit 1;
> 1 row in set (0.00 sec)
> ```
> 
> ```
> mysql> explain select * from videos where ts >= '2017-05-12 17:45:20' order by ts asc limit 1;
> +----+-------------+--------+-------+---------------+------+---------+------+------+-----------------------+
> | id | select_type | table  | type  | possible_keys | key  | key_len | ref  | rows | Extra                 |
> +----+-------------+--------+-------+---------------+------+---------+------+------+-----------------------+
> |  1 | SIMPLE      | videos | range | ts            | ts   | 4       | NULL | 1127 | Using index condition |
> +----+-------------+--------+-------+---------------+------+---------+------+------+-----------------------+
> ```





https://stackdev.space/questions/what-are-some-ways-to-improve-the-performance-of-this-mysql-sql-query
