### ISSUE TITLE
Can't instal developer dependencies because docker-api 1.32.0 requires ruby 2.0

### ISSUE THREAD

**Issue by prehor** [logstash-plugins/logstash-input-jdbc#167]
logstash-plugin install --development wants to install logstash-input-jdbc dependency docker-api. docker-api release 1.32.0, which was released on Oct 2, requires ruby 2.0 or higher, so it can't be installed on jruby incorporated in logstash.

Please could you set maximum docker-api version to 1.31.0 or remove docker-api development dependency if it's not need?

- Version: 2.4.0
- Operating System: Debian Jesse from official Logstash docker image
- Steps to Reproduce: logstash-plugin install --development

**Comment by suyograo** [comment]
Fixing it here: https://github.com/logstash-plugins/logstash-input-jdbc/pull/168
