### ISSUE TITLE
[logstash-input-jdbc]: double import line

### ISSUE THREAD

**Issue by joschi99** [logstash-plugins/logstash-input-jdbc#178]
The jdbc import is starting every minute. The last row from the previous import is imported with the new import again. This means that on every import job we have 1 double row.

![2016-11-18 09_38_16-monitoring all service status - kibana](https://cloud.githubusercontent.com/assets/6400595/20423818/e84e5f48-ad72-11e6-83af-5e5b2c004967.png)

```
  jdbc {
    jdbc_validate_connection => true
    jdbc_connection_string => "jdbc:mysql://localhost:3306/centreon_storage"
    jdbc_user => "backup"
    jdbc_password => "mFRiQYIuwHhCIk6s753Q"
    jdbc_driver_library => "/etc/logstash/jdbc/mysql-connector-java-5.1.39-bin.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    statement_filepath => "/etc/logstash/sql/centreon-service-status.sql"
    last_run_metadata_path => "/tmp/logstash-centreon-service-status.lastrun"
    record_last_run => true
    use_column_value => true
    tracking_column => "last_check"
    schedule => "* * * * *"
    tags => [ "jdbc", "centreon", "mariadb", "service" ]
    type => "centreon-service-status"
  }
```
In the SQL we use the function sql_last_value
```
SELECT *
FROM
services AS s,
hosts AS h
WHERE
s.host_id = h.host_id AND s.enabled = 1
AND h.enabled = 1
AND s.last_check > :sql_last_value
```

s.last_check is a unix time. I tried also to convert the unix time in human time and with `use_column_value => false`, but always the same result. The data in the table is not persistent and will updated every time, but on every update the timestamp on s.last_check is updated to actual time.

- Version: Logstash 5.0.1
- Operating System: CentOS 6.8

What I doing wrong?

**Comment by guyboertje** [comment]
Please post this question on our discuss forum. You can reopen this if the discussion there concludes that it is a bug.

https://discuss.elastic.co/c/logstash
