### ISSUE TITLE
config option sequel_opts is not merged correctly into the opts hash in jdbc_connect

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-input-jdbc#189]
Sequel expects all of its options as symbolised keys.

Logstash config will capture `sequel_opts` with string keys that simply get ignored by Sequel.

**Comment by wiibaa** [comment]
@guyboertje are you 100% sure and have an example of options that are not respected. as normally Sequel is *massaging* the options hash internally and calling **to_sym** by itself https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/connecting.rb#L61-L65

**Comment by guyboertje** [comment]
@wiibaa - you are correct, it does symbolize keys. I was having some problems figuring out the correct answer to the elastic/support-dev-help issue linked before.

**Comment by guyboertje** [comment]
Closing this as irrelevant.
