### ISSUE TITLE
Does logstash-input-jdbc support the multiple data sources in a jdbc-es.conf file?

### ISSUE THREAD

**Issue by Judyccb** [logstash-plugins/logstash-input-jdbc#190]
Hi,

I want to import data from several data sources of oracle 11.23 to es 2.3.3,and want all config info is provided by only a jdbc-es.conf file ,does  logstash-input-jdbc support it? If yes,could you give an example about it?

**Comment by GlenRSmith** [comment]
@Judyccb 
We try to restrict the github Issues for reports of possible defects.
For assistance in usage, it's better to post a question on [the discuss boards](https://discuss.elastic.co/) or to join the #logstash channel on IRC on freenode. You are for more likely to have your question noticed and responded to in those places, too!
