### ISSUE TITLE
JDBC automatically convert some int column to boolean

### ISSUE THREAD

**Issue by snowwolf007cn** [logstash-plugins/logstash-input-jdbc#195]
I have some column declared as unsigned tinyint(1) in MariaDB. The data selected will be automatically converted to boolean. I don't find any settings to disable it. So I had to set the column to unsigned tinyint(2), which makes logstash read the data correctly. Hope this could be fixed.

**Comment by Leviathans** [comment]
who can fix it pls

**Comment by soarhu** [comment]
@snowwolf007cn @Leviathans  It's not a bug.you can append a settings to your jdbc url.
eg:jdbc.url=jdbc:mysql://127.0.0.1:3306/testdb?tinyInt1isBit=false

**Comment by dfzhou6** [comment]
@soarhu good solution! thanks!
