### ISSUE TITLE
MySQL JDBC LoadError: no such file to load

### ISSUE THREAD

**Issue by edceo** [logstash-plugins/logstash-input-jdbc#198]
Hi,

**logstash.conf**
`input {
  jdbc {
    jdbc_driver_library => "/home/edsoft/IdeaProjects/docker-elk/resources/mysql-connector-java-5.1.36-bin.jar"
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		jdbc_connection_string => "jdbc:mysql://localhost:3306/yazilimokulu"
		jdbc_user => "root"
		jdbc_password => "1"
		schedule => "* * * * *"
		statement => "select * from posts"
	}
	tcp {
		port => 5000
	}
}`

**Dockerfile**
`
FROM docker.elastic.co/logstash/logstash:5.2.2
RUN logstash-plugin install logstash-input-jdbc`

This is my logstash.conf file. And when I build the Dockerfile always throw  LoadError: no such file to load error for jdbc_driver_library. Please help me thanks

**Comment by kirrie** [comment]
add a line to Dockerfile like this.

```dockerfile
FROM docker.elastic.co/logstash/logstash:5.2.2
RUN logstash-plugin install logstash-input-jdbc
ADD mysql-connector-java-5.1.36-bin.jar /usr/share/logstash/mysql-connector-java-5.1.36-bin.jar
```
and jdbc_driver_library should be like this. 
```
jdbc_driver_library => "/usr/share/logstash/mysql-connector-java-5.1.36-bin.jar"
```

**Comment by guyboertje** [comment]
Solution given as above. Closing.
