### ISSUE TITLE
ERROR logstash.agent - Pipeline aborted due to error , SQLServerException: Login failed for user

### ISSUE THREAD

**Issue by gprasanth93** [logstash-plugins/logstash-input-jdbc#213]
Hi Guys,

I am using Logstash-5.2.1 and trying to connect to SQL Server 2012

User has Windows Authentication , to connect to SQL does it SQL authentication ?

Error snippet : **ComMicrosoftSqlserverJdbc::SQLServerException: Login failed for user 'hbeu'.** 

**Using below Config in Logstash**
input {
jdbc {
jdbc_driver_library => "C:/Bin/logstash-5.2.1/sqljdbc_4.2/enu/jre8/sqljdbc42.jar"
jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
jdbc_connection_string => "jdbc:sqlserver://Server:Port;databaseName=[DatabaseName];"
jdbc_user => "hbeu"
jdbc_password => ""
}
}
filter {
}
output {
elasticsearch {
hosts => "localhost:9200"
index => "DataMax"
document_type => "DataMax"
}
stdout {
codec => rubydebug
}
}

**Error :**

C:\Bin\logstash-5.2.1\logstash-5.2.1\bin>logstash -f C:\Bin\logstash-5.2.1\logstash-5.2.1\config\SqlServer.config
Could not find log4j2 configuration at path /Bin/logstash-5.2.1/logstash-5.2.1/config/log4j2.properties. Using default config which logs to console
15:10:11.314 [[main]-pipeline-manager] ERROR logstash.agent - Pipeline aborted due to error {:exception=>#<Sequel::DatabaseConnectionError: Java::ComMicrosoftSqlserverJdbc::SQLServerException: Login failed for user 'hbeu'. ClientConnectionId:1b30a5cf-50eb-4013-952b-4d50aef8c4d0>, :backt
race=>["com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(com/microsoft/sqlserver/jdbc/SQLServerException.java:217)", "com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(com/microsoft/sqlserver/jdbc/tdsparser.java:251)", "com.microsoft.sqlserver.jdbc.TDSParser.parse(com/microsoft
/sqlserver/jdbc/tdsparser.java:81)", "com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:3080)", "com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:2361)", "com.microsoft.sqlserve
r.jdbc.SQLServerConnection.access$100(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:44)", "com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:2347)", "com.microsoft.sqlserver.jdbc.TDSCommand.execute(com/microsoft/sqls
erver/jdbc/IOBuffer.java:6276)", "com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:1794)", "com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:1405)", "com.microsoft
.sqlserver.jdbc.SQLServerConnection.login(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:1069)", "com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(com/microsoft/sqlserver/jdbc/SQLServerConnection.java:905)", "com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(com/microso
ft/sqlserver/jdbc/SQLServerConnection.java:452)", "com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(com/microsoft/sqlserver/jdbc/SQLServerDriver.java:1014)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "RUBY.connect(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jru
by/1.9/gems/sequel-4.43.0/lib/sequel/adapters/jdbc.rb:222)", "RUBY.make_new(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/connection_pool.rb:116)", "RUBY.make_new(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/c
onnection_pool/threaded.rb:228)", "RUBY.available(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/connection_pool/threaded.rb:201)", "RUBY._acquire(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/connection_pool/th
readed.rb:137)", "RUBY.acquire(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/connection_pool/threaded.rb:151)", "RUBY.sync(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/connection_pool/threaded.rb:282)", "org.j
ruby.ext.thread.Mutex.synchronize(org/jruby/ext/thread/Mutex.java:149)", "RUBY.sync(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/connection_pool/threaded.rb:282)", "RUBY.acquire(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.4
3.0/lib/sequel/connection_pool/threaded.rb:150)", "RUBY.hold(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/connection_pool/threaded.rb:106)", "RUBY.synchronize(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/data
base/connecting.rb:285)", "RUBY.test_connection(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/sequel-4.43.0/lib/sequel/database/connecting.rb:295)", "RUBY.prepare_jdbc_connection(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/logstash-input-jdbc-4.1.3/lib/logst
ash/plugin_mixins/jdbc.rb:171)", "RUBY.register(C:/Bin/logstash-5.2.1/logstash-5.2.1/vendor/bundle/jruby/1.9/gems/logstash-input-jdbc-4.1.3/lib/logstash/inputs/jdbc.rb:191)", "RUBY.start_inputs(C:/Bin/logstash-5.2.1/logstash-5.2.1/logstash-core/lib/logstash/pipeline.rb:358)", "org.jruby.RubyArray.ea
ch(org/jruby/RubyArray.java:1613)", "RUBY.start_inputs(C:/Bin/logstash-5.2.1/logstash-5.2.1/logstash-core/lib/logstash/pipeline.rb:357)", "RUBY.start_workers(C:/Bin/logstash-5.2.1/logstash-5.2.1/logstash-core/lib/logstash/pipeline.rb:233)", "RUBY.run(C:/Bin/logstash-5.2.1/logstash-5.2.1/logstash-cor
e/lib/logstash/pipeline.rb:188)", "RUBY.start_pipeline(C:/Bin/logstash-5.2.1/logstash-5.2.1/logstash-core/lib/logstash/agent.rb:302)", "java.lang.Thread.run(java/lang/Thread.java:745)"]}
15:10:11.429 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
15:10:14.348 [LogStash::Runner] WARN  logstash.agent - stopping pipeline {:id=>"main"}

**Comment by guyboertje** [comment]
@gprasanth93 Using MSSQL integrated security is a complex subject. We have very little experience with this and do not have the hardware and software to setup a test lab to educate ourselves. Please do a Google search for "JDBC integrated auth Windows SQL Server 2012".
