### ISSUE TITLE
How index nested type from db?

### ISSUE THREAD

**Issue by amydong** [logstash-plugins/logstash-input-jdbc#218]
I want to get array type date from postgresql, and save in ElasticSearch with nested type.

①Mapping

          "test_arr1" : {						
            "type": "nested",						
            "properties" : {						
              "name1": {						
                "type": "text"						
              },						
              "name2": {						
                "type": "text"						
              }						
            }						
          },						
          "test_arr2" : {						
            "type": "nested",						
            "properties" : {						
              "arr1": {						
                "type": "text"						
              },						
              "arr2": {						
                "type": "text"						
              },						
              "arr3": {						
                "type": "text"						
              }						

②Postgresql
  select * from test_mc1;
   id | type  |  name  | content |   test_arr1   |             test_arr2
----+-------+--------+---------+---------------+------------------------------------
  1 | type1 | machao | AAAAA   | {test3,test4} | {{a1,a2,a3},{a4,a5,a6},{a7,a8,a9}}

but I get next error when I start logstash,how can I save array data to ES's nested tyep?
please help.

[2017-06-05T17:38:00,369][WARN ][logstash.outputs.elasticsearch] Failed action. {:status=>400, :action=>["index", {:_id=>"1", :_index=>"machao", :_type=>"type1", :_routing=>nil}, 2017-06-05T09:38:00.288Z %{host} %{message}], :response=>{"index"=>{"_index"=>"machao", "_type"=>"type1", "_id"=>"1", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [test_arr1] tried to parse field [null] as object, but found a concrete value"}}}}

**Comment by guyboertje** [comment]
Please raise this question on our discuss forum - this is not a JBDC input bug per se.

https://discuss.elastic.co/c/logstash
