### ISSUE TITLE
Two bugs in "#open_jdbc_connection" when rescuing a DatabaseConnectionError

### ISSUE THREAD

**Issue by guyboertje** [logstash-plugins/logstash-input-jdbc#220]
In the `open_jdbc_connection` method.

1. `close_jdbc_connection` is called on `@database` - it has no such method.
2. The logged warning does not capture valuable JDBC Driver messages/trace that may be in the DatabaseConnectionError instance.

**Comment by avihaleva** [comment]
Does reconnect works in any scenario ? Looks like when their is any error on the connection, the connection will never recover. Is there any workaround for this issue ?  Can I cause Logstash to terminate on such error ?

**Comment by franklauterwald** [comment]
@avihaleva I just created pull request #231 which solves the reconnection issue for us. Can you try if it helps you? It is supposed to fix reconnecting

**Comment by guyboertje** [comment]
Closed with https://github.com/logstash-plugins/logstash-input-jdbc/pull/231

**Comment by guyboertje** [comment]
@avihaleva @franklauterwald \
New version of plugin published, thank you.
