### ISSUE TITLE
ERROR: Something went wrong when installing /logstash-1.0/logstash-input-jdbc-4.2.4.gem, message: Connection refused

### ISSUE THREAD

**Issue by jiehuang** [logstash-plugins/logstash-input-jdbc#240]
I want to install logstash-input-jdbc in offline server, and when I install an offline plugin pack just like:

bin/logstash-plugin install logstash-input-jdbc-master.zip 

ERROR: Something went wrong when installing logstash-input-jdbc-master.zip, message: Connection refused - Connection refused

or

bin/logstash-plugin install logstash-input-jdbc-4.2.4.gem

it runs :
ERROR: Something went wrong when installing xxx/logstash-input-jdbc-4.2.4.gem, message: Connection refused - Connection refused

what's the matter ?
thanks all

**Comment by jsvd** [comment]
when installing a plugin pack please use the file schema syntax:

`bin/logstash-plugin install file:///tmp/logstash-input-jdbc-master.zip`

Also described in the docs: https://www.elastic.co/guide/en/logstash/current/offline-plugins.html#installing-offline-packs
