### ISSUE TITLE
logstash-input-jdbc  support any version ES ?

### ISSUE THREAD

**Issue by LockGit** [logstash-plugins/logstash-input-jdbc#244]
I think this repository README.md file should write support ES version list .
my ES version number is  "5.2.2", lucene_version is "6.4.1" ,
the plugin support this version ?

**Comment by dmarkhas** [comment]
This is an *input* plugin that reads data from JDBC, it has no direct bearing to ElasticSearch.

**Comment by LockGit** [comment]
yep, I've already used it in production environments !  thx
