### ISSUE TITLE
ES have HTTP Basic Authentication , How to config it's ?

### ISSUE THREAD

**Issue by LockGit** [logstash-plugins/logstash-input-jdbc#245]
my ES have HTTP Basic Authentication , so I can't use this plugin ?

I try to set  config.conf file  hosts => "user:pass@127.0.0.1:9223"   ,  when run logstash -f ./config.conf will get errors

How to fix it ?

**Comment by LockGit** [comment]
I find logstash-core/lib/logstash/modules/logstash_config.rb file line 65:
` 
 def elasticsearch_output_config(type_string = nil)
    hosts = array_to_string(get_setting(LogStash::Setting::SplittableStringArray.new("var.elasticsearch.hosts", String, ["localhost:9200"])))
    index = "#{@name}-#{setting("var.elasticsearch.index_suffix", "%{+YYYY.MM.dd}")}"
    user = @settings["var.elasticsearch.username"]
    password = @settings["var.elasticsearch.password"]
    lines = ["hosts => #{hosts}", "index => \"#{index}\""]
    lines.push(user ? "user => \"#{user}\"" : nil)
    lines.push(password ? "password => \"#{password}\"" : nil)
    lines.push(type_string ? "document_type => #{type_string}" : nil)
    lines.push("ssl => #{@settings.fetch('var.elasticsearch.ssl.enabled', false)}")
`

    user = @settings["var.elasticsearch.username"]
    password = @settings["var.elasticsearch.password"]
---
so i guess config file output option can set username=xxxx ,  password=xxxxx

**Comment by guyboertje** [comment]
Created in the wrong repo. Closing, if this is still a problem, ask in the [Elastic Logstash Discuss](https://discuss.elastic.co/c/logstash) forum
