### ISSUE TITLE
DatabaseDisconnectError，execute sql statement timeout

### ISSUE THREAD

**Issue by huangyongchao** [logstash-plugins/logstash-input-jdbc#250]
this is my input config:
input {
  jdbc {
    schedule => "* * * * *"
    jdbc_driver_library => "/Users/huangyongchao/soft/elasticsearch-6.0.0/lib/mysql.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    parameters => { "update_time" => "2010-10-10 00:00:00" }
    statement => "select concat('1703-',id) id, concat(year(start_date),month(start_date)) mm, date(start_date) dd, str_to_date(start_date,'%Y-%c-%d %h:%i:%s') start_date,file_name_ori, file_name_confirm, data_source_type, ifnull(data_type,'cps') data_type, advertiser_id, advertiser_name, campaign_id, campaign_name, link_id, earner_id, earner_name, advertiser_website_id, website_id, website_name, order_no, product_no, product_name, commision_type, total_amount, valid_amount, action_no, action_price, total_money, deduct_money, actual_money,  end_date, feed_back_tag, agent_ip, is_expired, confirm_total_amount, confirm_valid_amount, confirm_total_money, confirm_actual_money, confirm_deduct_money, total_commision, eqifa_commision, website_commision, data_status, sys_total_commision, sys_eqifa_commision, sys_website_commision, actual_total_commision, actual_eqifa_commision, actual_website_commision, commision_id, confirm_status, confirm_operator_id, confirm_operator_name, confirm_time, confirm_no, submit_status, submit_time, submit_operator_id, submit_operator_name, settlement_status, settlement_time, settlement_operator_id, settlement_operator_name, create_time, update_time, action_ip, ori_confirm_operator_id, ori_confirm_operator_name, ori_confirm_time, data_desc, product_type, commision_id_type, op_rate, actual_op_rate, gwk_tag, ifnull(false_order_flag,0), false_order_update_time, false_order_operator_name, ifnull(platform,'y') platform, feed_back_key, spm, click_time, ifnull(click_terminal_type,0) click_terminal_type, ifnull(click_mobile_type,0) click_mobile_type, ifnull(click_market_type,0) click_market_type, commision_rule, commision_group, order_extend_info, parent_order_no, ifnull(is_parent_order,0) is_parent_order,MD5(concat(campaign_id,'|',website_id,'|',order_no,'|',product_no,'|',commision_type)) union_id from  cps_effect_confirm_log_1703  where update_time >= convert_tz(:sql_last_value, '+00:00','+08:00')"
    use_column_value => true
    tracking_column => "update_time"
    tracking_column_type => "timestamp"
    jdbc_paging_enabled => true
    jdbc_page_size => 500
    id => "id"
    type => "1703"
  }
} 

my execute statement  data more then 1000 0000 rows, 
but the jdbc plugins must be  execute select count(*)  from  (my statement) is so slowly ,so exceptions

how can I do ???

**Comment by guyboertje** [comment]
The underlying tech needs a count to work out how to do paging `jdbc_paging_enabled => true`.

I suggest that you add your own `LIMIT 500` type clause and remove paging.
