### ISSUE TITLE
jdbc input plugin add string "TIMESTAMP" to tracking column :sql_last_value

### ISSUE THREAD

**Issue by ampelio** [logstash-plugins/logstash-input-jdbc#253]
Version: logstash 6.0.1
filter input:
.......
last_run_metadata_path => "/etc/logstash/last_run/cmd_total"
sql_log_level => "debug"
use_column_value => true
tracking_column_type => "timestamp"
tracking_column => "end_date"
....................

last_run: cmd_total
--- 2017-12-07 21:39:59.000000000 +01:00

Query:
...............
and end_date > to_date(substr(:sql_last_value,1,16), 'YYYY-MM-DD HH24:MI')

Output Replacement:
and end_date > to_date(substr(TIMESTAMP '2017-12-07 21:09:59.000000 +01:00',1,16), 'YYYY-MM-DD HH24:MI')

Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLDataException: ORA-01858: a non-numeric character was found where a numeric was expected

In my opinion the word "TIMESTAMP" must not be present

Oracle Db version 11.

Please ckeck.

BR, Andrea

**Comment by ampelio** [comment]
Version: logstash 6.0.1
input:
        last_run_metadata_path => "/etc/logstash/last_run/cmd_total"
        sql_log_level => "debug"
        use_column_value => true
        tracking_column_type => "timestamp"
        tracking_column => "end_date"

last_run: cmd_total
--- 2017-12-07 21:39:59.000000000 +01:00

Query:
and end_date > to_date(substr(:sql_last_value,1,16), 'YYYY-MM-DD HH24:MI')

Output Replacement:
and end_date > to_date(substr(TIMESTAMP '2017-12-07 21:09:59.000000 +01:00',1,16), 'YYYY-MM-DD HH24:MI')

Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLDataException: ORA-01858: a non-numeric character was found where a numeric was expected

Please ckeck.

BR, Andrea

**Comment by guyboertje** [comment]
This is correct. From [the docs](https://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements003.htm#SQLRF51049), this is the way to specify a timestamp literal.

> TIMESTAMP Literals 
The TIMESTAMP datatype stores year, month, day, hour, minute, and second, and fractional second values. When you specify TIMESTAMP as a literal, the fractional_seconds_precision value can be any number of digits up to 9, as follows:
> 
> TIMESTAMP '1997-01-31 09:26:50.124'
