### ISSUE TITLE
How to use time variables in statement

### ISSUE THREAD

**Issue by orgliny** [logstash-plugins/logstash-input-jdbc#289]
How to achieve the following functions？
```
input {
  jdbc {
    #...
    statement => "select * from table_%{+yyyyMM}"
    #...
  }
}
```

**Comment by yaauie** [comment]
The sprintf format strings do not work in Logstash inputs because they use the current event's context to produce a string. Since inputs are responsible for _creating_ events for logstash to process, there is no "current event" at the time that they are executed.
