### ISSUE TITLE
Monitor and continue data ship from mysql database to es

### ISSUE THREAD

**Issue by ipchaube** [logstash-plugins/logstash-input-jdbc#303]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:
bin/logstash -f logstash.cof
This command is doing job  but getting terminated and I have to run again. Please tell me if their is a way that can keep running this command so whenever data change in mysql can get updated to es automatically.

- Version: logstash 6.4.0
- Operating System: Ubantu
- Config File (if you have sensitive info, please remove it):
input {
    jdbc {
        jdbc_connection_string => "jdbc:postgresql://localhost:5432/mydb"
        jdbc_user => "postgres"
        jdbc_validate_connection => true
        jdbc_driver_library => "/path/to/postgresql-9.4-1201.jdbc41.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        statement => "SELECT * from logstable"
    }
}
output {
    elasticsearch {
        hosts => "<>"
        index => "contacts"
        document_type => "contact"
        document_id => "%{iid}"
        
    }
}
- Sample Data:
NA
- Steps to Reproduce:

run below cammand
bin/logstash -f logstash.cof
This command is doing job  but getting terminated and I have to run again. Please tell me if their is a way that can keep running this command so whenever data change in mysql can get updated to es automatically.

**Comment by guyboertje** [comment]
Use the schedule setting. The docs explain it well enough.

Closing. Please use the forum if you have further questions.
