### ISSUE TITLE
MsSQL JDBC driver cant find class

### ISSUE THREAD

**Issue by kwhat** [logstash-plugins/logstash-input-jdbc#31]
More frustration with the input plugin side of things. "Error: net.sourceforge.jtds.jdbc.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?"  So /Users/user/jar/jtds-1.3.1.jar exists and contains the class net.sourceforge.jtds.jdbc.Driver.  Same setup works with other DB apps.

```
input {
	jdbc {
		jdbc_driver_library => "/Users/user/jar/jtds-1.3.1.jar"
		jdbc_driver_class => "net.sourceforge.jtds.jdbc.Driver"
		jdbc_connection_string => "jdbc:jtds:sqlserver://..."
		jdbc_user => "user"
		jdbc_password => "pass"
		statement => "SELECT TOP 1000 ..."
		jdbc_page_size => 10000
		jdbc_paging_enabled => true
	}
}
```

**Comment by kwhat** [comment]
This is a non-issue.

**Comment by suyograo** [comment]
@kwhat just curious, what was the problem?

**Comment by kwhat** [comment]
The short of it was I was making modifications to the wrong file because I am new to OS X and they refuse to provide full path names.  Ex:  ~/Downloads/logstash... vs ~/projects/logstash...  #fail
