### ISSUE TITLE
how can i use this plugin to input one table into multi index

### ISSUE THREAD

**Issue by linuxclay** [logstash-plugins/logstash-input-jdbc#310]
Hi all,i have question.
The question is that i have a table in mysql and then i use this plugin to translate date to elasticsearch.
The data in mysql is diff by vendor id ,i want to put these data to elasticsearch per vendor per index.
how can i use multi index ? @guyboertje please help me ,thank you !  -_-

**Comment by guyboertje** [comment]
@linuxclay 

The elasticsearch output has a [dynamic index name facility](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index).

Closing this, if you need more help, please post your question to https://discuss.elastic.co/c/logstash

These issues are intended for bug reports or code improvements.
