### ISSUE TITLE
Scheduling issue - is it possible to run query a minute after the previous query finished?

### ISSUE THREAD

**Issue by Kamarey** [logstash-plugins/logstash-input-jdbc#338]
I asked this question on the Elastic forum, but it was ignored, so I'm posting same question here:

[https://discuss.elastic.co/t/jdbc-input-scheduling-issue-is-it-possible-to-run-query-a-minute-after-the-previous-query-finished/185568](https://discuss.elastic.co/t/jdbc-input-scheduling-issue-is-it-possible-to-run-query-a-minute-after-the-previous-query-finished/185568)

**Comment by Kamarey** [comment]
A comment or something? Anyone is here?

**Comment by robbavey** [comment]
Unfortunately this functionality is not supported in this plugin at this time.
