### ISSUE TITLE
JTDS not working

### ISSUE THREAD

**Issue by agareppe** [logstash-plugins/logstash-input-jdbc#34]
I configured JTDS Driver to connect to SQLServer but I got this error:

Error: net.sourceforge.jtds.jdbc.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
You may be interested in the '--configtest' flag which you can
use to validate logstash's configuration before you choose

configured like this:
jdbc {
                jdbc_driver_library => "/opt/logstash/lib/jtds-1.3.1-linkedserver-2.jar"
                jdbc_driver_class => "net.sourceforge.jtds.jdbc.Driver"
                jdbc_connection_string => "jdbc:jtds:sqlserver://SERVERDB:1433;DatabaseName=database;domain=MYDOMAIN;appName=LogstashAG.JTDS;socketKeepAlive=true"
                jdbc_user => "USER"
                jdbc_password => "sdfsdf"
                schedule => "0/1 \* \* \* *"
                parameters => { "initial_date" => "2015-06-29 00:00:00.000" }
                statement => "select EventTime, Value, CounterType from tabe (nolock) where EventTime > :initial_date and  EventTime > :sql_last_start"
                type => "stats_DB"
        }

**Comment by pafq** [comment]
@agareppe 

When I use this plugin in the begining, I had a problem like that. I solve modifying the jdbc_driver_class.
Try this: jdbc_driver_class => "Java::net.sourceforge.jtds.jdbc.Driver"

**Comment by s-loiseau** [comment]
Thank you pafq, i was struggling on these setting

**Comment by p-nandi** [comment]
Just trying to understand, if the Java:: prefix needs to be there for all JDBC drivers? I am trying to configure a custom JDBC driver but getting the same error. I tried removing the Java:: prefix but still it didn't work. But when I un-jar the JDBC jar file I can see the driver is present and the driver works fine across multiple projects but only with Logstash, I am getting this error.
Is there any other things that I can do to trubleshoot?

**Comment by guyboertje** [comment]
@p-nandi 
I have never seen the `Java::` prefix in use.
See http://jtds.sourceforge.net/faq.html#classNotFound
```
ClassNotFoundError is thrown by the classloader when it can not find a certain class. In this case it's the net.sourceforge.jtds.jdbc.Driver class, which means that jtds.jar is not in the classpath
```
I our case we manually load the jar from the path specified in `jdbc_driver_library` and the class must be found therein.

**Comment by afewnotes** [comment]
> @p-nandi
> I have never seen the `Java::` prefix in use.
> See http://jtds.sourceforge.net/faq.html#classNotFound
> 
> ```
> ClassNotFoundError is thrown by the classloader when it can not find a certain class. In this case it's the net.sourceforge.jtds.jdbc.Driver class, which means that jtds.jar is not in the classpath
> ```
> 
> I our case we manually load the jar from the path specified in `jdbc_driver_library` and the class must be found therein.

This `Java::` prefix just solved my problem :)
