### ISSUE TITLE
Add predefined parameters and format them.

### ISSUE THREAD

**Issue by golabk** [logstash-plugins/logstash-input-jdbc#35]
It will be useful for build query statement with predefined parameters
sql_last_end - the last time a statement was finished.
sql_current_start - the current time a statement was started.

Also, will be useful, if the predefined parameters can be converted to specific output format.
Conversion may look, for example:
parameters_format => [
"name", "format", "time_zone"
]
name - parameter name
format - parameter output format
time_zone - optional and can be specified with name or utc_offset

parameters_format => [
"sql_current_start", "%H:%M:%S", "",
"sql_last_start", "%d/%m/%Y %H:%M:%S", "+09:00",
"sql_last_end", "%Y-%m-%dT%H:%M:%S", "CST"
]

**Comment by pafq** [comment]
@golabk 

I think you can use the filter date to accomplish that.
Something like:

input {
   jdbc {
       ....
   }
}

filter {
  date {
    match  => [ "SavedTS", "YYYY-MM-dd HH:mm:ss Z" ]
    target => "SavedTS"
  }
}

output {
  stdout { codec => rubydebug }
}

**Comment by golabk** [comment]
@pafq

Thanks for the reply.

I use the parameter :sql_last_start in query statement and I need to convert it.
If the parameter :sql_last_start can be converted then the query will be simple.

My workaround e.g.
SELECT * FROM table WHERE minute_id>=TO_CHAR(FROM_TZ(CAST(TO_TIMESTAMP_TZ(:sql_last_start,'YY/MM/DD HH24:MI:SS,ff TZH:TZM') AS TIMESTAMP),'UTC') AT TIME ZONE DBTIMEZONE -1/1440,'HH24MI') and minute_id<TO_CHAR(FROM_TZ(CAST(TO_TIMESTAMP_TZ(:sql_last_start,'YY/MM/DD HH24:MI:SS,ff TZH:TZM') AS TIMESTAMP),'UTC') AT TIME ZONE DBTIMEZONE,'HH24MI')

If there were parameters sql_last_end, sql_current_start then I could write a statement, which needed.

**Comment by MichaelLiZhou** [comment]
@golabk 

I am no expert in dbs so your work around does it apply to the time format that is currently being stored?
 i.e. --- 2015-08-07 13:12:19.206000000 Z
Which is doesn't look maybe mines is storing in a different format. 

because when I just do a regular compare as such there is a few minutes of discrepancy
select * from log where creation_time > :sql_last_start

**Comment by golabk** [comment]
@MichaelLiZhou 

Yes,

thats the problem, the date and time is not stored in database in DATE, TIMESTAMP datatype.
They are stored in field VARCHAR2. I cannot change, because the database is external system.

**Comment by pafq** [comment]
@golabk 

So your only chance is to convert the String value to Date.
Could you give an example about the format store in Database and which RBDS system are you using?

**Comment by golabk** [comment]
@pafq 

Date format YYYYMMDD e.g. 20150812
Time format HH24MI e.g. 1636
RDBMS: Oracle Database 11g Enterprise Edition Release 11.2.0.2.0 - 64bit

**Comment by pafq** [comment]
@golabk 

You could try use something like this:

Cast(TO_TIMESTAMP (SubStr(:sql_last_start , 0, Length(:sql_last_start )-2), 'YYYY-MM-DD HH24:MI:SS.FF') As Date)

to filter your the record by date.
I don't try this.

**Comment by golabk** [comment]
@pafq 

It works, but only in UTC+0:00 time zone because the time in :sql_last_start is in UTC format.
My time zone is CET/CEST and :sql_last_start must be converted to this time zone.

**Comment by pafq** [comment]
@golabk 
You can try to convert your Date Field to UTC and then you can compare with the :sql_last_date.
You can convert you field using this:

from_tz(CAST(dateField AS TIMESTAMP),'CET') at TIME zone 'UTC'

**Comment by blavoie** [comment]
If I understand correctly the original poster I have the same problem with Oracle. Maybe, the same thing can happen to others RDBMS.

The sql_last_start field, when passed to my query (in my case) is like this: 
15-09-23 12:10:00,012000000 +00:00. 

I got this by creating a field in my query: 
'*' || :sql_last_start || '*'

But this format isn't understood by Oracle:
select to_date('15-09-23 12:10:00,012000000 +00:00') from dual
               *
Error at line 1
ORA-01830: date format picture ends before converting entire input string

It would be nice to force a date format and timezone for the sql_last_start when passed to the query. It's error prone to make parsing and conversion on this string. And it's especially harder if the format is dependant on environment running the logstash daemon.

**Comment by guyboertje** [comment]
I believe these questions have been answered
