### ISSUE TITLE
how to set array into elasticsearch

### ISSUE THREAD

**Issue by lgq1** [logstash-plugins/logstash-input-jdbc#358]
I user this plugin to sync mysql to elasticsearch,but I have some problems。
For example：my field is topics。
mysql format： topics:["girl","beatiful"]
es: topics: "["girl","beatiful"]",this is a string。

but I want is: ["girl","beatiful"],this is a array

please,how to do it?

**Comment by robbavey** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
