### ISSUE TITLE
logstash7.1同步oracle时区问题

### ISSUE THREAD

**Issue by hg199705** [logstash-plugins/logstash-input-jdbc#359]
我用的logstash7.1版同步oracle数据到es中，oracle中date（yyyy-mm-dd hh24:mi:ss）字段同步后都成了yyyy-mm-dd‘T’16:00:00.000Z格式，应该没有同步过来时分秒并早8小时的时间。不知道如何解决。

**Comment by kares** [comment]
for anyone not familiar with Chinese here's a translation :
> I use logstash 7.1 to synchronize oracle data to es, the date (yyyy-mm-dd hh24: mi: ss) field in oracle has become yyyy-mm-dd'T'16: 00: 00.000Z format , There should be no synchronization over hours, minutes, seconds, and 8 hours earlier. Don't know how to solve it.

not sure what exactly is causing you issues but we generally recommend you ask questions in our [forum](https://discuss.elastic.co/c/logstash) and leave the tracker for errors and bug reports. maybe you could try re-phrasing the question there.
