### ISSUE TITLE
Timestamp type not being filtered

### ISSUE THREAD

**Issue by MichaelLiZhou** [logstash-plugins/logstash-input-jdbc#36]
I am using Oracle jdbc and trying to get the date filter to work but there has been many issues. 
Here is my current config -->> at first it was a class error now its fine. Then there were incompatible types ruby and java strings. So I added the to_char. Now its not recognizing the timestamp. Could it be because of the type?  

 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
CREATION_TIME                             NOT NULL TIMESTAMP(6)

input {
  jdbc {
    jdbc_driver_library => "logstash-1.5.0/ojdbc6.jar"
    jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
    jdbc_connection_string => "jdbc:oracle:thin:@//"
    jdbc_user => ""
    jdbc_password => ""

    statement => "SELECT to_char(creation_time,'YYYY-MM-dd HH24:MI:SSxFF TZR') as logStoreTime from log where creation_time > :sql_last_start"
    record_last_run => true
    last_run_metadata_path => "/.logstash_jdbc_last_run"
    type => "log"
  }
}

filter {
  grok {
    match => {"logStoreTime" => "(?<logStoreTime>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{6} \+\d{2}:\d{2})"}
  }
    # date {
    #   locale => "en"
    #   timezone => "GMT"
    #   match => [
    #     "logStoreTime" , "YYYY-MM-dd HH:mm:ss.SSSSSS Z"
    #   ]
    # }

}

sample output of what I am getting: 
{
    "logstoretime" => "2015-08-04 18:34:14.747000 +00:00",
        "@version" => "1",
      "@timestamp" => "2015-08-06T12:52:15.850Z",
            "type" => "test",
            "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
    "logstoretime" => "2015-08-04 18:34:18.661000 +00:00",
        "@version" => "1",
      "@timestamp" => "2015-08-06T12:52:15.854Z",
            "type" => "test",
            "tags" => [
        [0] "_grokparsefailure"
    ]
}

And I know the grok pattern will match it has been tested on http://grokdebug.herokuapp.com/

**Comment by talevy** [comment]
to match the `logstoretime` field into the `@timestamp` field, there is no need for grok parsing it.

here is an example config you can check out to see it run through parsing the timestamp

```
input {
  generator {
    lines => ["2015-08-04 18:34:18.644000 +00:00"]
    count => 1
  }
}
filter {
  date {
    match => ["message", "YYYY-MM-dd HH:mm:ss.SSSSSS Z"]
  }
}
output {
  stdout { codec => rubydebug }
}
```

output : 
```
{
    "message" => "2015-08-04 18:34:18.644000 +00:00",
    "@timestamp" => "2015-08-04T18:34:18.644Z"
}
```

Through this test, I believe this time format string should work: `YYYY-MM-dd HH:mm:ss.SSSSSS Z`

**Comment by MichaelLiZhou** [comment]
I understand. I only put the grok match to see if its picking up from the table and its not! I even tried setting it to greedydata and it will not print out the field name I set. Here is what I changed with a mix of your code:

input {
  jdbc {
    jdbc_driver_library => "/logstash-1.5.0/ojdbc6.jar"
    jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
    jdbc_connection_string => "jdbc:oracle:thin:@//"
    jdbc_user => ""
    jdbc_password => ""

    statement => "SELECT to_char(creation_time,'YYYY-MM-dd HH24:MI:SSxFF TZR') as StoreTime from log where creation_time > :sql_last_start"
    record_last_run => true
    last_run_metadata_path => "/sincedbpath/.logstash_jdbc_last_run"
    type => "test"
  }
}

filter{
  grok {
    match => {"StoreTime" => "%{GREEDYDATA:logStoreTime}"}
  }
  date {
    match => ["logStoreTime", "YYYY-MM-dd HH:mm:ss.SSSSSS Z"]
  }
}
output{
  stdout {codec => rubydebug}
}

What I get:
{
     "storetime" => "2015-08-04 18:34:18.661000 +00:00",
      "@version" => "1",
    "@timestamp" => "2015-08-06T17:51:44.348Z",
          "type" => "test"
}

If I try with bare-bone config -> same input with jdbc but with your filter and output its the same:
{
     "storetime" => "2015-08-04 18:34:18.661000 +00:00",
      "@version" => "1",
    "@timestamp" => "2015-08-06T17:56:44.676Z",
          "type" => "test"
}

Do you think it could be the data type? Really frustrating problem especially when I know everything else is working properly.
