### ISSUE TITLE
com.mysql.jdbc.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?

### ISSUE THREAD

**Issue by jaycGong** [logstash-plugins/logstash-input-jdbc#364]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:
if you have de problem like this:
com.mysql.jdbc.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
you will make sure your driver jar  come from maven or other correct place download, then you should move the jdbc.driver .jar  to the place put all jar,for example:
logstash-7.4.2\logstash-core\lib\jars\

- Version: Logstash 7.4.2， jdbc driver：5.1.48
- Operating System: windows 10
- Config File (if you have sensitive info, please remove it):
- Sample Data: no data
- Steps to Reproduce:
start with:       logstash.bat -f ../mysql/mysql.conf

**Comment by liangxiong3403** [comment]
1.put jdbc.jar into LOGSTASH_HOME/logstash-core/lib/jars/your-mysql.jar;
2.comment logstash.conf's  jdbc_driver_library property

**Comment by robbavey** [comment]
@jaycGong Driver loading issues should be using the latest (4.3.19) version of this plugin, and ensuring that the `:jdbc_driver_library` property is set correctly with the full path to the required jar files.
