### ISSUE TITLE
jdbc input plugin cannot be found after sucessful installation

### ISSUE THREAD

**Issue by TianyunWu** [logstash-plugins/logstash-input-jdbc#38]
Hi, all. I am a newbie to both logstash and RubyGems, and now I am stuck setting up my logstash pipeline. Please leave a comment if you might know what went wrong. 
After the installation of jdbc input plugin on my Amazon EC2 servre, the plugin still could not be found during the configuration verification: 

$ bin/logstash -f simple-out.conf --configtest
The error reported is: 
  Couldn't find any input plugin named 'jdbc'. Are you sure this is correct? Trying to load the jdbc input plugin resulted in this error: no such file to load -- logstash/inputs/jdbc

Gemfile at Logstash home directory shows:
gem "logstash-input-jdbc", "1.0.0", :path => "vendor/local_gems/d8836756/logstash-input-jdbc-1.0.0"

Therefore, it looks to me that the installation is fine.

**Comment by pafq** [comment]
@TianyunWu 

do you check if "vendor/local_gems/d8836756/logstash-input-jdbc-1.0.0" really exists?

**Comment by TianyunWu** [comment]
@pafq
Yes, the folder indeed exists. 
I was not able to use the command "bin/plugin install logstash-input-jdbc" because my aws server cannot connect to RubyGems.org via ssl connections. My installation commands are as follows:
# cd /opt/logstash
# wget https://github.com/logstash-plugins/logstash-input-jdbc/archive/master.zip
# unzip master.zip
# cd logstash-input-jdbc-master
# gem build logstash-input-jdbc.gemspec
(output:
fatal: Not a git repository (or any of the parent directories): .git
  Successfully built RubyGem
  Name: logstash-input-jdbc
  Version: 1.0.0
  File: logstash-input-jdbc-1.0.0.gem)
# mv logstash-input-jdbc-1.0.0.gem /opt/logstash/
# cd ..
# bin/plugin install logstash-input-jdbc-1.0.0.gem
(output:
Validating logstash-input-jdbc-1.0.0.gem
Installing logstash-input-jdbc
Installation successful)

**Comment by pafq** [comment]
@TianyunWu 

I install one version of input-jdbc like you and work fine to me.
I'll try to make your steps. Please share your "simple-out.conf"

**Comment by TianyunWu** [comment]
@pafq, Sure!
Here it is:

# file: simple-out.conf
input {
	jdbc {
		# mysql jdbc connection string to our backup databse
		jdbc_connection_string => "jdbc:mysql://my_database_ip_address:3306/my_database"
		# the user we wish to excute our statement as
		jdbc_user => "my_username"
		jdbc_password => "my_password"
		# the path to our downloaded jdbc driver
		jdbc_driver_library => "/opt/logstash/mysql-connector-java-5.1.36-bin.jar"
		# the name of the driver class for mysql
		jdbc_driver_class => "com.mysql.jdbc.Driver"
		statement => "select * from source_list"
	}
}
output {
	stdout { codec => json_lines }
}

**Comment by pafq** [comment]
@TianyunWu 

I follow your steps and get the same error.
Please check the content of your folder  "vendor/local_gems/d8836756/logstash-input-jdbc-1.0.0".
Is the folder empty?

**Comment by childe** [comment]
i follow TianyunWu's steps, and vendor/local_gems/d8836756/logstash-input-jdbc-1.0.0 is empty.

**Comment by pafq** [comment]
@TianyunWu @childe 

I allready found whats wrong.
In "logstash-input-jdbc.gemspec" file you can find this line:

       s.files = `git ls-files`.split($\)

This will collect all the file mark in git to be packaged. With this line is requeired to have the Git Repository configure.
In your case, you don't have the git repository configured so when you execute the command "git ls-files" you don't get the list of files.

You have two ways to solve this:

   1 - Get Repository from Github:
               git clone https://github.com/logstash-plugins/logstash-input-jdbc.git
               cd logstash-input-jdbc
               gem build logstash-input-jdbc.gemspec

   2 - Replace on "logstash-input-jdbc.gemspec" command "git ls-files" for another that is valid on you SO that produce this output:

.gitignore
CHANGELOG.md
Gemfile
LICENSE
NOTICE.TXT
README.md
Rakefile
lib/logstash/inputs/jdbc.rb
lib/logstash/plugin_mixins/jdbc.rb
logstash-input-jdbc.gemspec
spec/inputs/jdbc_spec.rb

**Comment by pafq** [comment]
@TianyunWu @childe 

Or simply replace this line:

s.files = `git ls-files`.split($\)

By:

s.files = [".gitignore", "CHANGELOG.md", "Gemfile", "LICENSE", "NOTICE.TXT", "README.md", "Rakefile", "lib/logstash/inputs/jdbc.rb", "lib/logstash/plugin_mixins/jdbc.rb", "logstash-input-jdbc.gemspec", "spec/inputs/jdbc_spec.rb"]

**Comment by TianyunWu** [comment]
@pafq @childe 
I used pafq's first approach (the "git clone" approach), it worked. 
However, building the gem required some dependency gems that were not on my server. I eventually solved the download/connection problem by changing the gem sources (from RubyGems to a trusted ruby gem server in my country) in the Gemfile of both logstash home directory and the cloned logstash-input-jdbc folder.  
I advice guys who have connection problems to RubyGem.org to first modify the gem source before proceeding with the installation process of this jdbc plugin.
Thank both of you for your kind help! Danke sehr!

**Comment by KetkiThosar** [comment]
Hi, I have followed all the steps and that have worked fine....However I am getting error at the last step..
command -    # bin/plugin install logstash-input-jdbc-4.1.1.gem
output --   Can only install contrib at this time... Exiting.
Can anybody tell me what is wrong here?

**Comment by newcomerswk** [comment]
what

**Comment by chenhao521314** [comment]
good~
