### ISSUE TITLE
Can't install in logstash 1.5 rc3

### ISSUE THREAD

**Issue by iemem15** [logstash-plugins/logstash-input-jdbc#4]
I'm tryin to install as follows but I always get an error

cilos@nowher:/cilos/opt/logstash-1.5.0-rc3/bin> DEBUG=1 ./plugin install logstash-input-jdbc
Validating logstash-input-jdbc
Installing logstash-input-jdbc
Plugin version conflict, aborting
Bundler::VersionConflict: Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-input-jdbc (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-input-jdbc (>= 0) java', in any of the sources.
               start at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/resolver.rb:203
             resolve at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/resolver.rb:182
             resolve at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:193
               specs at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:132
   resolve_remotely! at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:121
                 run at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/installer.rb:79
             install at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/installer.rb:18
                 run at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/cli/install.rb:80
             install at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/cli.rb:157
                 run at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27
      invoke_command at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
            dispatch at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359
               start at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440
               start at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/cli.rb:10
     invoke_bundler! at /cilos/opt/logstash-1.5.0-rc3/lib/logstash/bundler.rb:109
                loop at org/jruby/RubyKernel.java:1507
     invoke_bundler! at /cilos/opt/logstash-1.5.0-rc3/lib/logstash/bundler.rb:106
                call at org/jruby/RubyProc.java:271
      capture_stdout at /cilos/opt/logstash-1.5.0-rc3/lib/logstash/bundler.rb:61
     invoke_bundler! at /cilos/opt/logstash-1.5.0-rc3/lib/logstash/bundler.rb:105
  install_gems_list! at /cilos/opt/logstash-1.5.0-rc3/lib/logstash/pluginmanager/install.rb:98
             execute at /cilos/opt/logstash-1.5.0-rc3/lib/logstash/pluginmanager/install.rb:34
                 run at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/command.rb:67
             execute at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/subcommand/execution.rb:11
                 run at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/command.rb:67
                 run at /cilos/opt/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/command.rb:132
              (root) at /cilos/opt/logstash-1.5.0-rc3/lib/logstash/pluginmanager.rb:12

**Comment by talevy** [comment]
Currently, there is no rubygem published for this plugin. This is more of a prototyped plugin. I am hoping to get feedback about it so we can improve it!

To test it out you will have to download this repo and add the following line to the `Gemfile` in the logstash-rc3 directory.

```
gem "logstash-input-jdbc", :path => "/path/to/logstash-input-jdbc"
```

This will have the plugin manager look into that directory to fetch the plugin when installing. then you may try and `bin/plugin install logstash-input-jdbc`.

does that make sense? Please let me know how that works out for you!


you may also be interested in learning more about the evolution of this plugin via this thread: https://github.com/elastic/logstash/issues/2476.

**Comment by iemem15** [comment]
Thnaks I'll try it


2015-04-30 16:51 GMT-05:00 Tal Levy <notifications@github.com>:

> Currently, there is no rubygem published for this plugin. This is more of
> a prototyped plugin. I am hoping to get feedback about it so we can improve
> it!
>
> To test it out you will have to download this repo and add the following
> line to the Gemfile in the logstash-rc3 directory.
>
> gem "logstash-input-jdbc", :path => "/path/to/logstash-input-jdbc"
>
> This will have the plugin manager look into that directory to fetch the
> plugin when installing. then you may try and bin/plugin install
> logstash-input-jdbc.
>
> does that make sense? Please let me know how that works out for you!
>
> you may also be interested in learning more about the evolution of this
> plugin via this thread: elastic/logstash#2476
> <https://github.com/elastic/logstash/issues/2476>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-input-jdbc/issues/4#issuecomment-97981810>
> .
>



-- 
Israel Elías Morales

**Comment by diije** [comment]
Hello,

I tried cloning the repo and adding the path to the plugin in `Gemfile` but I still get this error:

	~$ ./bin/plugin install logstash-input-jdbc
	Validating logstash-input-jdbc
	Installing logstash-input-jdbc
	Plugin version conflict, aborting
	ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash":
	  In Gemfile:
	    logstash-input-jdbc (>= 0) java depends on
	      logstash (< 2.0.0, >= 1.4.0) java
	Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-input-jdbc (>= 0) java', in any of the sources.


Any idea ?

Thanks !

**Comment by talevy** [comment]
Apologies for the late reply to this ticket. We have paused work on this during the Logstash 1.5 release. Plans are to get back to working on this to get it out of "prototype" status and something that we have battle-tested and can recommend for your use cases.

I have updated the repo to build against logstash 1.5. To install you can download the repo. and do the following within your Logstash 1.5 directory.

1. edit the main `Gemfile` to point to your local `logstash-input-jdbc` repo
```
# Gemfile
gem 'logstash-input-jdbc', :path => '/path/to/logstash-input-jdbc'
```

2. Install local plugin
```
# from main logstash dir
bin/plugin install --no-verify
```

plugin should now be installed.

**Comment by talevy** [comment]
@iemem15 @diije If you don't mind sharing your use-cases, they would help tremendously in building out better support for specific databases and new features! Thanks!

**Comment by diije** [comment]
Hello,

I still get the same error.

I started from a clean install:  

    wget http://download.elastic.co/logstash/logstash/logstash-1.5.0.tar.gz  
    tar -xzvf logstash-1.5.0.tar.gz  
    git clone https://github.com/logstash-plugins/logstash-input-jdbc  
    cd logstash  
    vi Gemfile

Added `gem "logstash-input-jdbc", :path => "/path/to/logstash-input-jdbc"` and closed the file, then:

    ~$ ./bin/plugin install --no-verify logstash-input-jdbc
    Installing logstash-input-jdbc
    Plugin version conflict, aborting
    ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash":
      In Gemfile:
        logstash-input-jdbc (>= 0) java depends on
          logstash (< 2.0.0, >= 1.4.0) java
    Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-input-jdbc (>= 0) java', in any of the sources.

My purpose is to use logstash as a forwarder from MySQL databases to elasticsearch, in order to use Grok to categorize URLs.  
Maybe that's not the smartest move, but I already have a logstash config file using Grok to categorize the same URLs, but from Apache log files.

**Comment by talevy** [comment]
you need not append `logstash-input-jdbc` to your `bin/plugin` command. The command will fetch any unfetched gems listed in the `Gemfile`. By adding `logstash-input-jdbc` you are telling the plugin installer to fetch the released version on rubygems, and not the local copy. try running `bin/plugin install --no-verify` instead, and that should do the trick.

This plugin is a prototype, so you may run into other issues along the way! But let me know how it goes! I am adding tests for mysql right now.

**Comment by diije** [comment]
Hello,

Thanks @talevy ! `bin/plugin install --no-verify` works perfectly to install this plugin.

I'm now trying to configure it properly but I think this issue can be closed.
And by the way, this config seems to work:

	input {
	  jdbc {
	    jdbc_driver_library => "/path/to/mysql-connector-java-5.1.33/mysql-connector-java-5.1.33-bin.jar"
	    jdbc_driver_class => "com.mysql.jdbc.Driver"
	    jdbc_connection_string => "jdbc:mysql://server:port/database"
	    jdbc_user => "user"
	    jdbc_password => "password"
	    statement => "SELECT * FROM table"
	  }
	}

**Comment by talevy** [comment]
awesome! you can use `:sql_last_start` to only `SELECT` newer elements if your `table` has a column with a datetime associated with the row.


I also published a new gem. so you can remove the local gem stuff in `Gemfile` and install `logstash-input-jdbc` normally

**Comment by kyunam** [comment]
I only see "Logstash startup completed" then nothing happens whether I use sql_last_start or not.
I use Logstash 1.5.0 and the configuration is,
input {
  jdbc {
    jdbc_driver_library => '/Users/someWhere/sqljdbc4.jar'
    jdbc_driver_class => 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    jdbc_connection_string => 'jdbc:sqlserver://myServer:1433;databaseName=myDB'
    jdbc_user => 'aUser'
    jdbc_password => 'aPassword'
    statement => 'SELECT * FROM LOGSTASH_POINT where CREATED_DATE > :sql_last_start'
    #parameters => { "sql_last_start" => "2014-01-01" }
    jdbc_validate_connection => true
    schedule => "* * * * *"
  }
}
output {
  stdout { codec => rubydebug }
}

Any help is appreciated.

**Comment by talevy** [comment]
@kyunam, it looks like you removed your comment... did you resolve your issue? what was the problem?

**Comment by kyunam** [comment]
Hi @talevy,
I thought it would be better to create a new issue, and then I created a new issue. :-)
thanks!
Q

**Comment by talevy** [comment]
@diije I am going to start making wrappers around this plugin for specific databases so you do not have to worry about the driver libraries. here is an example of the mysql one: https://github.com/talevy/logstash-input-mysql.


Closing this ticket

**Comment by jumpinjan** [comment]
Sweet!   If you need someone to test the Oracle flavor – please let me know…

I work with Oracle 11g  (11.2.0.4)

Janice



Janice Gluck

[cid:image001.png@01CF858C.32055680]<http://www1.good.com/>[http://media.www1.good.com/images/icon-em-sig-facebook.png]<https://www.facebook.com/goodformobile>[http://media.www1.good.com/images/icon-em-sig-twitter.png]<https://twitter.com/GOOD_technology>[http://media.www1.good.com/images/icon-em-sig-linkedin.png]<https://www.linkedin.com/company/good-technology>[http://media.www1.good.com/images/icon-em-sig-youtube.png]<https://www.youtube.com/user/GoodForMobile>
