### ISSUE TITLE
Not able to install logstash-input-jdbc-1.0.0.gem

### ISSUE THREAD

**Issue by vivekbhu** [logstash-plugins/logstash-input-jdbc#40]
HI Team,

   I have downloaded logstash-input-jdbc-1.0.0.gem from https://rubygems.org/gems/logstash-input-jdbc/versions/1.0.0.

Then I tried to run following command:
C:\Vivek\Investment Platform\ELK\logstash-1.5.3\logstash-1.5.3\bin>plugin install logstash-input-jdbc-1.0.0.gem

Below was the error, Please help me in resolving the issue.
_________________________________________________________________
io/console not supported; tty will not be manipulated
Validating logstash-input-jdbc-1.0.0.gem
Installing logstash-input-jdbc
Error Bundler::GemspecError, retrying 1/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 2/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 3/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 4/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 5/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 6/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 7/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 8/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 9/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 10/10
There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'
Too many retries, aborting, caused by Bundler::GemspecError
ERROR: Installation Aborted, message: There was a Errno::ENOENT while loading logstash-input-jdbc.gemspec:
No such file or directory - git from
  C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec:13:in `eval_gemspec'

**Comment by vivekbhu** [comment]
Just a note, I am a java developer and very new to Ruby so may be I am missing something here.

**Comment by pafq** [comment]
@vivekbhu 
What version of Ruby are you using?

**Comment by vivekbhu** [comment]
Ruby 1.9

**Comment by pafq** [comment]
@vivekbhu 

Try to update Ruby to version ruby 2.2.2p95
I follow your steps using this version and the all process work fine.

**Comment by vivekbhu** [comment]
@pafq , I have upgraded my ruby but still no luck. I am getting the same error.

**Comment by pafq** [comment]
@vivekbhu 
I try again and work fine to me. But i'm using Ubuntu.
From the error you can see that the problem is in line 13 from file C:/Vivek/Investment Platform/ELK/logstash-1.5.3/logstash-1.5.3/vendor/local_gems/5aff99d1/logstash-input-jdbc-1.0.0/logstash-input-jdbc.gemspec

Line 13 on my machine is a GIT command. It don't make sense to me, but if you don't have git install, try to install.
