### ISSUE TITLE
Commit state at every iteration

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-input-jdbc#41]
Currently the `.logtstash_since_lastrun` file is only updated to disk upon pipeline shutdown. This should be run after every sql run.

**Comment by alcir** [comment]
+1

**Comment by seahsiungee** [comment]
+1

Persisting the sql last start file after every sql run is crucial for clustering logstash nodes, supposedly if 1 of the node crashes, the sql last start will not be updated and retrieval of subsequent data will not be precise. Is there any work around for this?

**Comment by alcir** [comment]
+1

**Comment by talevy** [comment]
This has been fixed by the following commit: https://github.com/logstash-plugins/logstash-input-jdbc/commit/bc37474b5ac692fc9bebb79d5cb236492f63f75c
