### ISSUE TITLE
Exception when executing JDBC query 

### ISSUE THREAD

**Issue by MichaelLiZhou** [logstash-plugins/logstash-input-jdbc#45]
I left logstash running with a scheduler set to \* \* \* \* \* come back the next day to see these errors:
They look harmless...

Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLRecoverableException: No more data to read from socket>, :level=>:warn}
1066833202 rufus-scheduler intercepted an error:
  1066833202   job:
  1066833202     Rufus::Scheduler::CronJob "\* \* \* \* *" {}
  1066833202   error:
  1066833202     1066833202
  1066833202     Java::JavaSql::SQLRecoverableException
  1066833202     Closed Connection
  136942014       oracle.jdbc.driver.PhysicalConnection.needLine(oracle/jdbc/driver/PhysicalConnection.java:6295)
  136942014       oracle.jdbc.driver.OracleStatement.closeOrCache(oracle/jdbc/driver/OracleStatement.java:1364)
  136942014       oracle.jdbc.driver.OracleStatement.close(oracle/jdbc/driver/OracleStatement.java:1343)
  136942014       oracle.jdbc.driver.OracleStatementWrapper.close(oracle/jdbc/driver/OracleStatementWrapper.java:100)
  136942014       java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
...

Exception when executing JDBC query {:exception=>#<Sequel::DatabaseDisconnectError: Java::JavaSql::SQLRecoverableException: Closed Connection>, :level=>:warn}

**Comment by talevy** [comment]
the connection closed... did it re-attempt to connect and execute the query for you?

**Comment by MichaelLiZhou** [comment]
No there were no attempts to connect again.

**Comment by MichaelLiZhou** [comment]
This just happened today:

 101692012 rufus-scheduler intercepted an error:
  101692012   job:
  101692012     Rufus::Scheduler::CronJob "* * * * *" {}
  101692012   error:
  101692012     101692012
  101692012     Java::JavaSql::SQLRecoverableException
  101692012     Closed Connection
  101692012       oracle.jdbc.driver.PhysicalConnection.needLine(oracle/jdbc/driver/PhysicalConnection.java:6295)
  101692012       oracle.jdbc.driver.OracleStatement.closeOrCache(oracle/jdbc/driver/OracleStatement.java:1364)
  101692012       oracle.jdbc.driver.OracleStatement.close(oracle/jdbc/driver/OracleStatement.java:1343)
  101692012       oracle.jdbc.driver.OracleStatementWrapper.close(oracle/jdbc/driver/OracleStatementWrapper.java:100)
  101692012       java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
  101692012       Sequel::JDBC::Database.statement(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:662)
  101692012       Sequel::JDBC::Database.statement(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:662)
  101692012       Sequel::JDBC::Database.execute(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:246)
  101692012       Sequel::JDBC::Database.execute(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:246)
  101692012       Sequel::ThreadedConnectionPool.hold(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:103)
  101692012       Sequel::ThreadedConnectionPool.hold(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:103)
  101692012       Sequel::ThreadedConnectionPool.hold(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:101)
  101692012       Sequel::ThreadedConnectionPool.hold(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:101)
  101692012       Sequel::Database.synchronize(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:254)
  101692012       Sequel::Database.synchronize(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:254)
  101692012       Sequel::JDBC::Database.execute(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:245)
  101692012       Sequel::JDBC::Database.execute(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:245)
  101692012       Sequel::Dataset.execute(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:921)
  101692012       Sequel::Dataset.execute(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:921)
  101692012       Sequel::JDBC::Dataset.fetch_rows(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:721)
  101692012       Sequel::JDBC::Dataset.fetch_rows(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/adapters/jdbc.rb:721)
  101692012       Sequel::Dataset.each(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:139)
  101692012       Sequel::Dataset.each(vendor/bundle/jruby/1.9/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:139)
  101692012       LogStash::PluginMixins::Jdbc.execute_statement(vendor/bundle/jruby/1.9/gems/logstash-input-jdbc-1.0.0/lib/logstash/plugin_mixins/jdbc.rb:118)
  101692012       LogStash::PluginMixins::Jdbc.execute_statement(vendor/bundle/jruby/1.9/gems/logstash-input-jdbc-1.0.0/lib/logstash/plugin_mixins/jdbc.rb:118)
  101692012       LogStash::Inputs::Jdbc.execute_query(vendor/bundle/jruby/1.9/gems/logstash-input-jdbc-1.0.0/lib/logstash/inputs/jdbc.rb:189)
  101692012       LogStash::Inputs::Jdbc.execute_query(vendor/bundle/jruby/1.9/gems/logstash-input-jdbc-1.0.0/lib/logstash/inputs/jdbc.rb:189)
  101692012       RUBY.run(vendor/bundle/jruby/1.9/gems/logstash-input-jdbc-1.0.0/lib/logstash/inputs/jdbc.rb:165)
  101692012       org.jruby.RubyProc.call(org/jruby/RubyProc.java:271)
  101692012       Rufus::Scheduler::Job.do_call(vendor/bundle/jruby/1.9/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234)
  101692012       Rufus::Scheduler::Job.do_call(vendor/bundle/jruby/1.9/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234)
  101692012       Rufus::Scheduler::Job.do_trigger(vendor/bundle/jruby/1.9/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258)
  101692012       Rufus::Scheduler::Job.do_trigger(vendor/bundle/jruby/1.9/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258)
  101692012       RUBY.start_work_thread(vendor/bundle/jruby/1.9/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300)
  101692012       org.jruby.RubyProc.call(org/jruby/RubyProc.java:271)
  101692012       RUBY.start_work_thread(vendor/bundle/jruby/1.9/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:299)
  101692012       org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1507)
  101692012       RUBY.start_work_thread(vendor/bundle/jruby/1.9/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289)
  101692012       java.lang.Thread.run(java/lang/Thread.java:745)
  101692012   tz:
  101692012     ENV['TZ']: 
  101692012     Time.now: 2015-09-15 10:56:00 -0400
  101692012   scheduler:
  101692012     object_id: 8040
  101692012     opts:
  101692012       {}
  101692012       frequency: 0.3
  101692012       scheduler_lock: #<Rufus::Scheduler::NullLock:0x52a56a40>
  101692012       trigger_lock: #<Rufus::Scheduler::NullLock:0x242a8624>
  101692012     uptime: 514966.491 (5d23h2m46s490)
  101692012     down?: false
  101692012     threads: 2
  101692012       thread: #<Thread:0x13a47dac>
  101692012       thread_key: rufus_scheduler_8040
  101692012       work_threads: 1
  101692012         active: 1
  101692012         vacant: 0
  101692012         max_work_threads: 28
  101692012       mutexes: {}
  101692012     jobs: 1
  101692012       at_jobs: 0
  101692012       in_jobs: 0
  101692012       every_jobs: 0
  101692012       interval_jobs: 0
  101692012       cron_jobs: 1
  101692012     running_jobs: 1
  101692012     work_queue: 0
} 101692012 .

**Comment by djgerhab** [comment]
I've been getting similar errors with my logstash JDBC connection that is scheduled to run once a day, seems like I get either a disconnect error or reset error. Some nights it works but I feel like I got a 60% chance of it failing for one connection reason or the another. I do have connection_retry_attempts set to 3 and a wait time for 10 secs in between. My DB resides in Azure if that any difference.

Here is what I have been seeing:

`Exception when executing JDBC query {:exception=>#<Sequel::DatabaseDisconnectError: Java::ComMicrosoftSqlserverJdbc::SQLServerException: The connection is closed`

`Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::ComMicrosoftSqlserverJdbc::SQLServerException: Connection reset>`

**Comment by sliontc** [comment]
Any solutions?

**Comment by razafinr** [comment]
See this pull request : #185  , I think it is the solution for problem

**Comment by suyograo** [comment]
Fixed in #185
