### ISSUE TITLE
last successfull got timestamp

### ISSUE THREAD

**Issue by nitram4** [logstash-plugins/logstash-input-jdbc#46]
i plan to use the plugin to collect logs from oracle database. since these logs are very sensitive incannot afford ang loose of data.
The situation is that as i understand currently this plugin stores only last run of the query but not actual timestamp of last data got. so when the logs appear after the run (due to delay of write to DB) then during next run the data will not be collected.

I suggest to have the option to select field (in timestamp format) and during each run the last value of this filed will be stored (instead of current time of last run or last run end) and during next run this value will be used as input,

**Comment by yokyo** [comment]
@nitram4 Hi,nitram4!
I come across the same problem as you now,have you any idea to resolve this?

**Comment by nitram4** [comment]
Hello, 
i have similiar java tool which I use to get data from DB to csv. Since i work with application logs I somethimes suffer with the issue that some logs enter the DB little bit later and within the cycle of fetching data from DB to csv i might loose them. So I have updated the tool (im not programmer, so I let my programmers to do it) and now it works like this:

1. I have xml file with the last successfull timestamp of last line from the fetch (exact value from database field)
2. when the tools cycle starts it reads the xml file and use the timestamp as parameter for where clause (where date_field between <parameter> and sysdate
3. after fetching the data the tool reads the output and looks for the last line and particular field vale in timestamp format and saves it into xml file (here is expected to have order by clause at the end of sql query in order to have last timestamp in last line)
4. waiting for next cycle

I hope i wrote it understandable, and hope that somebody will add this feature into this plugin because after that it will be usefull also for logs (it is not now)
