### ISSUE TITLE
URL wrong for install

### ISSUE THREAD

**Issue by jtal** [logstash-plugins/logstash-input-jdbc#49]
From elasticsearch directory I do `bin/plugin install logstash-input-jdbc`

But it fails because it cant find the file. Noticed the "null".

https://github.com/null/logstash-input-jdbc/archive/master.zip

I used the --url param to replace "null" with "logstash-plugins" and it seems to have installed properly.

**Comment by markwalkom** [comment]
Worked ok for me;
```
$ logstash-1.5.4/bin/plugin install logstash-input-jdbc
Validating logstash-input-jdbc
Installing logstash-input-jdbc
Installation successful
```

What version are you on? Please also post the entire command and the output you got.

**Comment by jtal** [comment]
elasticsearch is 1.7.1, I just downloaded it, installed marvel, then some guy on irc told me to try logstash for my rdbms importing needs:

```
21:34:51-jtal~/stuff/elasticsearch-1.7.1$ bin/plugin install logstash-input-jdbc --verbose
-> Installing logstash-input-jdbc...
Trying https://github.com/null/logstash-input-jdbc/archive/master.zip...
Failed: IOException[Can't get https://github.com/null/logstash-input-jdbc/archive/master.zip to /home/jtal/stuff/elasticsearch-1.7.1/plugins/logstash-input-jdbc.zip]; nested: FileNotFoundException[https://github.com/null/logstash-input-jdbc/archive/master.zip]; nested: FileNotFoundException[https://github.com/null/logstash-input-jdbc/archive/master.zip]; 
Failed to install logstash-input-jdbc, reason: failed to download out of all possible locations..., use --verbose to get detailed information
```

**Comment by markwalkom** [comment]
Ahh, see this is a Logstash plugin not an Elasticsearch one.
So you need to download and install Logstash as well, then install that plugin :)

**Comment by jtal** [comment]
Let's never speak of this again. Thanks for the help.

**Comment by suyograo** [comment]
@jtal no worries, this is common :) Thanks @markwalkom

**Comment by agacem** [comment]
Sorry, but ELastic documentation(S) should be more clear ... here specifing $LOGSTASH_DIR/bin/plugin ...etc is not so big effort while plugin binary exist under elasticsearch directory too....
Thx 2 markwalkom.
