### ISSUE TITLE
Show "Installation successful",but not included in "plugin list" output.

### ISSUE THREAD

**Issue by yokyo** [logstash-plugins/logstash-input-jdbc#55]
Env : win7 64bit,  jdk8,  jruby1,9 comes with logstash1.5.4

1. I build this project first, finally "logstash-input-jdbc-2.0.0.gem" generated.
2.  copy logstash-input-jdbc-2.0.0.gem to bin folder, run " plugin install logstash-input-jdbc-2.0.0.gem" :
<pre><code>>plugin install logstash-input-jdbc-2.0.0.gem
io/console not supported; tty will not be manipulated
Validating logstash-input-jdbc-2.0.0.gem
Installing logstash-input-jdbc-2.2.0.gem
Installation successful</code></pre>
and i found one line appended in Gemfile
<pre><code>gem "logstash-input-jdbc", "2.0.0", :path => "vendor/local_gems/5a5a4930/logstash-input-jdbc-2.0.0"</code></pre>
but nothing in folder "vendor\local_gems\5a5a4930\logstash-input-jdbc-2.0.0\"
3.  run "plugin list", "logstash-input-jdbc" didnt show up.
   
PS.I just doubt that why a plugin like this not intergrated by default?

**Comment by guyboertje** [comment]
logstash-input-jdbc is included in LS 2 by default.
