### ISSUE TITLE
logstash is not reconnecting

### ISSUE THREAD

**Issue by scaarup** [logstash-plugins/logstash-input-jdbc#56]
I am using this plugin to connect to a Sybase ASE 15.7 database. I am executing a stored procedure and in that procedure I have a "kill-if-already-running". If this is executed, the jdbc connection is killed by the database-server. Logstash never reconnects and I have to restart logstash to get things running again.

**Comment by talevy** [comment]
thanks for reporting this. This is an important feature that will be worked on

**Comment by suyograo** [comment]
PR: https://github.com/logstash-plugins/logstash-input-jdbc/pull/92
