### ISSUE TITLE
Can jdbc input plugin excute several sql in one config ?

### ISSUE THREAD

**Issue by jinleileiking** [logstash-plugins/logstash-input-jdbc#58]
And put into several index/types.

**Comment by talevy** [comment]
Not at the moment. to execute multiple queries, you can simply add another `jdbc` input to your config. your elasticsearch output plugin can support dynamic index names and types based on dynamic field referencing.

**Comment by maurojosedmjr** [comment]
Is it possible now?
@talevy @jinleileiking

**Comment by talevy** [comment]
Not exactly, You can either write separate queries in different plugin instances in the pipeline, or you can write UNION queries that compose multiple queries into one
