### ISSUE TITLE
SELECT command denied to user 'username'@'logstash_server' exception

### ISSUE THREAD

**Issue by SrikanthKS** [logstash-plugins/logstash-input-jdbc#60]
I am not sure if it's an issue but more of a use case I think. So here's what's happening - 

i have installed Logstash on one server and my database on which I am writing the SELECT query is on a different server. So when I run Logstash with JDBC plugin, I get the SELECT command denied for my username exception. Here's my config -

		input {
			jdbc {
				jdbc_connection_string => "jdbc:mysql://database_server:port/"
				jdbc_user => "username"
				jdbc_password => "password"
				jdbc_validate_connection => true
				jdbc_driver_library => "/tmp/mysql-connector-java-5.0.8-bin.jar"
				jdbc_driver_class => "com.mysql.jdbc.Driver"
				statement => "SELECT * from database.table where time > now() - interval 1 minute"
			}
		}

		output {

		   elasticsearch {
										cluster => "ClusterName"
										host => "hostName"
										protocol => "transport"
										port => "9300"
										index => "logstash-%{+YYYY.MM.dd}"
										workers => 4
		   }
		   stdout {
				codec => rubydebug
		   }
		}

Wehn I run logstash process with this configuration on logstash_server, I get the following exception - 

     Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::ComMysqlJdbcExceptions::MySQLSyntaxErrorException: SELECT command denied to user 'username'@'logstash_server' for table 'table'>, :level=>:warn}

Does that mean I need Logstash to be installed on database_server itself? Can't Logstash installed on a remote server connect to the database_server using the jdbc_connection_string?

Thanks!

**Comment by itarafath** [comment]
same issue here

**Comment by suyograo** [comment]
Of course LS can be installed on a separate server from the DB. Are you sure you have the right permissions setup on the DB end?

**Comment by suyograo** [comment]
Also, can we move this to our [forum](https://discuss.elastic.co/c/logstash)? The forum is also the best place to debug config issues, getting help etc. Github is mainly used for issues/enhancements. Thanks!
