### ISSUE TITLE
Include number of records fetched per statement in debug logging

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-jdbc#61]
Currently, at debug logging level, we write out the SQL statements with parameters that are being issued by the plugin, it will also be helpful to write out a count of the # of records returned by each specific statement.

**Comment by talevy** [comment]
in addition to this. `sql_log_level` option should be exposed in the plugin to have Sequel's log level for logging sql statements reflect that of Logstash's.
