### ISSUE TITLE
seed being updated even when JDBC query fails?

### ISSUE THREAD

**Issue by rb36135** [logstash-plugins/logstash-input-jdbc#72]
# cat seed_swd_consumer_resourcelist
 --- 2015-10-22 18:00:38.718000000 Z

 # /opt/logstash/bin/logstash -f /etc/logstash/conf.d/jdbc-perfdb-consumer-swd.conf
 Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError:   Java::JavaSql::SQLSyntaxErrorException: ORA-00904: "CRA"."CLUSTER_NAME_CRA2": invalid identifier>, :level=>:warn}
 Logstash startup completed
 Logstash shutdown completed

 # cat seed_swd_consumer_resourcelist
 --- 2015-10-22 19:40:24.348000000 Z

**Comment by purbon** [comment]
Thanks for your report, this makes sense to fix as might led to some, even if not happening often, a data loss.

**Comment by a-k-** [comment]
we had the same issue, addressed with https://github.com/logstash-plugins/logstash-input-jdbc/pull/94

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-jdbc/pull/94
