### ISSUE TITLE
Can't load driver 

### ISSUE THREAD

**Issue by vikassaini860** [logstash-plugins/logstash-input-jdbc#78]
# file: contacts-index-logstash.conf   
input {
    jdbc {
        jdbc_connection_string => "jdbc:oracle:thin:@//192.168.54.74:1521/od6oracle"
        jdbc_user => "od6oracle"
        jdbc_password => "od6oracle"
        jdbc_validate_connection => true
        jdbc_driver_library => "C:\Users\vikas.saini\Desktop\easy search\ojdbc7.jar"
        jdbc_driver_class => "java::oracle.jdbc.driver.OracleDriver"
        statement => "SELECT * from PDBDOCUMENT"
    }
}
output {
    elasticsearch {
        index => "contacts"
        document_type => "contact"
        document_id => "%{uid}"
        hosts => "127.0.0.1:9200"
    }
}

**Comment by markwalkom** [comment]
What's the error? What versions?
If you'd like some help please provide more information.

**Comment by vikassaini860** [comment]
ok java 1.7 i am using .
error is "can't load oracle.jdbc.driver.OracleDriver" please check you have included correct jar in jdbc libarary string

**Comment by markwalkom** [comment]
What LS version? However this doesn't sound like a bug, more of a misconfiguration issue.

So please join us in #logstash on Freenode or at https://discuss.elastic.co/ for troubleshooting help or general questions. 
We reserve Github for confirmed bugs and feature requests :)
