### ISSUE TITLE
oracle.jdbc.OracleDriver not loaded

### ISSUE THREAD

**Issue by szabog74** [logstash-plugins/logstash-input-jdbc#8]
Hi,

I'm trying to use this plugin with ojdbc7.jar with no success. Error message is 
The only error reported is in debug mode:
  oracle.jdbc.OracleDriver not loaded

used config:

  input {
    jdbc {
      jdbc_driver_library => '/home/<full path>/ojdbc7.jar'
      jdbc_driver_class => 'oracle.jdbc.OracleDriver'
      jdbc_connection_string => 'abc'
      statement => 'def'
    }
  }

Any idea? Already tried with ojdbc6.jar, same story.

thanks

**Comment by WiWa** [comment]
Possibly try jdbc_driver_class => 'Java::oracle.jdbc.driver.OracleDriver'
My reasoning comes from the ruby sequel adapter this plugin uses: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/jdbc/oracle.rb

**Comment by talevy** [comment]
is this not yet resolved?

**Comment by suyograo** [comment]
@WiWa please reopen this issue if you see it again

**Comment by szabog74** [comment]
works fine, thanks. the jdbc_connection_string should be "jdbc:oracle:thin:@//host:port/database"

**Comment by vikassaini860** [comment]
# file: contacts-index-logstash.conf  my configuration file and its shows me the same error driver can't be loaded !
input {
    jdbc {
        jdbc_connection_string => "jdbc:oracle:thin:@//192.168.54.74:1521/od6oracle"
        jdbc_user => "od6oracle"
        jdbc_password => "od6oracle"
        jdbc_validate_connection => true
        jdbc_driver_library => "C:\Users\vikas.saini\Desktop\easy search\ojdbc7.jar"
        jdbc_driver_class => "java::oracle.jdbc.driver.OracleDriver"
        statement => "SELECT * from PDBDOCUMENT"
    }
}
output {
    elasticsearch {
        index => "contacts"
        document_type => "contact"
        document_id => "%{uid}"
        hosts => "127.0.0.1:9200"
    }
}

**Comment by sjyun** [comment]
Java::oracle.jdbc.driver.OracleDriver it is work for me.
how about use UpperCase 'j'

**Comment by hellogbx** [comment]
Java::oracle.jdbc.driver.OracleDriver it is work for me.
how about use UpperCase 'j'
