### ISSUE TITLE
Logtsash-ES Data Check

### ISSUE THREAD

**Issue by srinvas** [logstash-plugins/logstash-input-jdbc#82]
I am currently using logstash-jdbc-plugin to pull data from DB and put it to an index in ES. How to check if the entire data pulled from DB is getting inserted into Elastic Search index.

The data that is pulled is in millions so can't keep checking manually

**Comment by purbon** [comment]
@srinvas thanks for your feedback, I don't think this is a problem that should be solved in here, is more or https://github.com/logstash-plugins/logstash-output-elasticsearch the elasticsearch output. Feel free to open an issue there.

BTW, LS is expected to log when data is not there. but would be nice add an issue there so we can discuss. 

thanks
