### ISSUE TITLE
jdbc_driver_library parameter should support array value

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-input-jdbc#85]
Sometimes, as is the case with Teradata, the JDBC driver libraries may consist of more than one jar, but the jdbc_driver_library parameter only supports a single argument.

```
terajdbc4.jar 
tdgssconfig.jar
```

Can this parameter be changed to support an array value?

**Comment by purbon** [comment]
Fixed in #86
