### ISSUE TITLE
sql_last_start isn't persisted when executing logstash as non-sevice

### ISSUE THREAD

**Issue by digitalpacman** [logstash-plugins/logstash-input-jdbc#88]
The only shutdown method implemented is "stop". You also need to implement "close". Sometimes "stop" isn't called and only "close" is. If you run logstash from the command line to do an import of data into elasticsearch, and at a future date want to run it again, but using the sql_last_start (like a monthly/weekly/daily job or something) then it'll never invoke the "stop" method of the plugin.

You should add the YAML.dump() command to the "close" method. I think the "stop" method shouldn't ever be used for this purpose, as it's not reliable.

This is what I did to just get my instance working now.

I added this to inputs/jdbc.rb below the "stop" method.

    def close
      puts "closing"
      # update state file for next run
      if @record_last_run
        File.write(@last_run_metadata_path, YAML.dump(@sql_last_start))
      end

      close_jdbc_connection
    end

**Comment by AvivRatzon** [comment]
This was a huge problem for and digitalpacman's code solved it. thank you :)

**Comment by talevy** [comment]
Commit https://github.com/logstash-plugins/logstash-input-jdbc/commit/bc37474b5ac692fc9bebb79d5cb236492f63f75c should fix this

**Comment by kaib** [comment]
is this in the new version which i get from plugin install?? For me the state is only persisted when i cancel the execution. When logstasg terminates on his own, then no state is commited

**Comment by untergeek** [comment]
@kaib If you have plugin version 3.0.0, then `sql_last_start` has been replaced by `sql_last_value`.  It's a breaking change, as is evidenced by the major version bump.  

Please see https://github.com/logstash-plugins/logstash-input-jdbc/issues/57#issuecomment-169436652 for more information.

**Comment by kaib** [comment]
@untergeek thanks for the super fast response its working perfekt with 3.0.0, any info about release date of this version?

**Comment by untergeek** [comment]
@kaib You mean, released in Logstash?  Hopefully next week we'll release 2.2, and this version will be included.

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-jdbc/issues/88
