### ISSUE TITLE
"Java::JavaLang::OutOfMemoryError: Java heap space" error

### ISSUE THREAD

**Issue by diije** [logstash-plugins/logstash-input-jdbc#9]
Hello,

As explained in an other issue, I use this plugin to import MySQL data into ElasticSearch.
Everything works fine as far as my query doesn't return more than 100 000 rows. When it does, I always get a "Java::JavaLang::OutOfMemoryError: Java heap space" error:

	Logstash startup completed
	Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaLang::OutOfMemoryError: Java heap space>, :level=>:warn}
	Logstash shutdown completed

I tried updating the heap space with `export JVM_ARGS="-Xms4096m -Xmx4096m"` but it doesn't seem to change anything.

Any idea on what to do to avoid this ?

My config file:  

    input {
      jdbc {
        jdbc_driver_library => "/path/to/mysql-connector-java-5.1.33-bin.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://host:port/database"
        jdbc_user => "user"
        jdbc_password => "password"
        statement => "SELECT ..."
      }
    }

    filter {
      [some filters here]
    }

    output {
      stdout {
        codec => rubydebug
      }
      elasticsearch_http {
        host => "host"
        index => "myindex"
      }
    }

**Comment by talevy** [comment]
your database query may be resulting in a very large number of rows returned. Paging has been added to relieve this pain.

you can go ahead and add 
```
jdbc {
   jdbc_paging_enabled => true,
   jdbc_page_size => 200000
}
```

and see how that works out. depending on how big each row is, different page sizes may work out better.

**Comment by diije** [comment]
Hello,

Seems to work, thanks.  
Just added some commas. 
Here is my config now:  

    input {
      jdbc {
        jdbc_driver_library => "/path/to/mysql-connector-java-5.1.33-bin.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://host:port/database"
        jdbc_user => "user"
        jdbc_password => "password"
        statement => "SELECT ..."
        jdbc_paging_enabled => "true"
        jdbc_page_size => "50000"
      }
    }

    filter {
      [some filters here]
    }

    output {
      stdout {
        codec => rubydebug
      }
      elasticsearch_http {
        host => "host"
        index => "myindex"
      }
    }

**Comment by daniele-pecora** [comment]
Time saver.
Solves my java heap space issue

**Comment by ohoroyoi** [comment]
life saver.
I love you forever  @diije

**Comment by gumelar26** [comment]
thank you guys
