### ISSUE TITLE
Copy one column in elasticsearch index into another column applying analyzers

### ISSUE THREAD

**Issue by srinvas** [logstash-plugins/logstash-input-jdbc#98]
I am using logstash jdbc plugin to insert data from db to already created custom index in elastic search. I have some columns in the index which are analyzed using custom analyzers.

For example I am getting column1 from database which is not analyzed. I have created two columns column2 and column3 for which analyzers are applied while creating an index. Now I want the same data of column1 to be copied into column2 and column3 while the data is being inserted.

I am using the following pattern while creating index:

"mappings": {   
       "itemsnew": {   
           "properties": {   
               "column1": {  
                   "type": "string",  
                   "copy_to": "column2",   
                   "copy_to": "column3"    
               },   
           "column2": {    
               "index_analyzer": "custom analyzer",   
               "search_analyzer": "standard",   
               "type": "string"   
           }    
       }    
   }  
Will the data get inserted into the column2 and column3 and will it be analyzed ?

**Comment by srinvas** [comment]
I have tried running this but I am not able to see the column2 and column3 as a columns displayed like column1. But when I am able to search data by selecting column2 and column3 in Structured query under match_all. 
1) How to display the columns : column2 and column3
2) How to check if the data is getting analysed or not ?

**Comment by srinvas** [comment]
@gmoskovicz can u provide any solution for this ?

**Comment by suyograo** [comment]
@srinvas can you please post this kind of question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements. Thanks!
